In [23]:
import requests

# ── Config ─────────────────────────────────────────────────────────────────
CTM_LIVE = "https://carbontransitionmodel.com/api/"
CTM_BETA = "https://beta.carbontransitionmodel.com/api/"

HEADERS = {
    "Content-Type": "application/json",
    "Model": "CTM",
}

# Clusters as named in the API
CLUSTERS = [
    "noord_nederland",
    "nzkg",
    "rotterdam_moerdijk",
    "zeeland_west_brabant",
    "chemelot",
    "cluster_6",
]

SECTORS = [
    "other_chemicals",
    "aluminium",
    "other_metals",
    "non_metallic_minerals",
    "transport_equipment",
    "machinery",
    "mining_and_quarrying",
    "food",
    "paper",
    "central_ict",
    "wood_and_wood_products",
    "construction",
    "textile_and_leather",
    "other",
]


FIELDS = [
    "enabled",
    "transformation",
    "electricity_demand",
    "natural_gas_demand",
    "hydrogen_(>98%_vol%)demand",
    "hydrogen(<98%_vol%)demand",
    "heat(<_100_c)demand",
    "heat(>_100_c)demand",
    "waste_gases_demand",
    "coal_and_coal_products_demand",
    "oil_and_oil_products_demand",
    "biomass(solid)demand",
    "biomass(liquid)demand",
    "green_gas_demand",
    "waste(fossil)demand",
    "waste(biogenic)demand",
    "ammonia_demand",
    "methanol_demand",
    "electricity_production",
    "natural_gas_production",
    "hydrogen(>98%_vol%)production",
    "hydrogen(<98%_vol%)production",
    "heat(<_100_c)production",
    "heat(>_100_c)production",
    "waste_gases_production",
    "coal_and_coal_products_production",
    "oil_and_oil_products_production",
    "biomass(solid)production",
    "biomass(liquid)production",
    "green_gas_production",
    "waste(fossil)production",
    "waste(biogenic)_production",
    "ammonia_production",
    "methanol_production",
    "co2_emissions_production",
    "methane_emissions_production",
    "n2o_emissions_production",
    "f_gas_emissions_production",
    "other_greenhouse_gas_emissions_production",
    "co2_fossil_demand",
    "co2_bio_demand",
    "co2_fossil_production",
    "co2_bio_production",
    "hybrid_heat_capacity",
    "chp_capacity",
    "chp_thermal_efficiency",
    "chp_electrical_efficiency",
    "hybrid_heat_flh",
    "chp_flh",
]



# ── Core API call ──────────────────────────────────────────────────────────

class CTMClient:
    def __init__(self, use_beta: bool = False):
        self.url            = CTM_BETA if use_beta else CTM_LIVE
        self.session_id     = None
        self.ms_graph_session = None

    def _call(self, payload: dict) -> dict:
        """Make a raw API call, reusing MSGraphSession for speed."""
        if self.ms_graph_session:
            payload["MSGraphSession"] = self.ms_graph_session
        response = requests.post(self.url, headers=HEADERS, json=payload)
        response.raise_for_status()
        data = response.json()
        # always update the graph session token
        self.ms_graph_session = data.get("MSGraphSession", self.ms_graph_session)
        if "warnings" in data:
            print(f"  [CTM warn] {data['warnings']}")
        return data

    # ── Session management ─────────────────────────────────────────────────

    def create_clean_sheet_session(self) -> str:
        """
        Create a session from base and immediately apply clean sheet settings.
        This disables all CTM built-in calculations so only explicitly set data
        is sent to the ETM.
        """
        # Step 1: create session from base
        data = self._call({"ScenarioID": "base", "outputs": []})
        self.session_id = data["SessionID"]
        print(f"Session created: {self.session_id}")

        # Step 2: apply clean sheet settings (disable all built-in calculations)
        self.set_inputs({
            "other_settings_other_industry_disable_inputs_input": "1",
            "other_settings_ctm_bottom_up_sites_input":           "1",
            "other_settings_disable_waste_incineration_to_etm_input": "1",
            "other_settings_fertilizers_to_chemicals_etm_input": "1",
        })
        print("Clean sheet applied.")
        return self.session_id

    def delete_session(self):
        """Permanently delete the current session."""
        if not self.session_id:
            return
        # deleteSession returns plain text, not JSON
        response = requests.post(
            self.url,
            headers=HEADERS,
            json={"SessionID": self.session_id, "special": ["deleteSession"]},
        )
        print(f"Session deleted: {response.text}")
        self.session_id     = None
        self.ms_graph_session = None

    # ── Inputs ─────────────────────────────────────────────────────────────

    def set_inputs(self, inputs: dict, outputs: list = None) -> dict:
        """Set one or more input values. Returns output values if requested."""
        data = self._call({
            "SessionID": self.session_id,
            "inputs":    inputs,
            "outputs":   outputs or [],
        })
        return data.get("output_values", {})

    # ── Data level helpers ─────────────────────────────────────────────────

    def set_sector(self, sector: str, column: str, value: str,
                   disable_clusters: bool = True):
        """
        Set a value at sector level and optionally disable all clusters
        to avoid ambiguity (recommended per docs).
        """
        inputs = {
            f"{sector}&&sector&&enabled":    "1",
            f"{sector}&&sector&&{column}":   value,
        }
        if disable_clusters:
            for cluster in CLUSTERS:
                inputs[f"{sector}&&{cluster}&&cluster&&enabled"] = "0"
        self.set_inputs(inputs)

    def set_cluster(self, sector: str, cluster: str, column: str, value: str,
                    disable_sector: bool = True):
        """
        Set a value at cluster level and optionally disable the sector level.
        """
        inputs = {
            f"{sector}&&{cluster}&&cluster&&enabled": "1",
            f"{sector}&&{cluster}&&cluster&&{column}": value,
        }
        if disable_sector:
            inputs[f"{sector}&&sector&&enabled"] = "0"
        self.set_inputs(inputs)

    def set_site(self, sector: str, cluster: str, site: str,
                 column_values: dict,
                 disable_sector: bool = True,
                 disable_cluster: bool = True):
        """
        Enable a site and set one or more column values for it.
        Optionally disable sector and cluster levels to avoid ambiguity.

        column_values: dict of {column: value}, e.g.
            {"electricity_demand": "100", "natural_gas_demand": "200"}
        """
        inputs = {
            f"{sector}&&{cluster}&&{site}&&enabled": "1",
        }
        for column, value in column_values.items():
            inputs[f"{sector}&&{cluster}&&{site}&&{column}"] = value

        if disable_sector:
            inputs[f"{sector}&&sector&&enabled"] = "0"
        if disable_cluster:
            inputs[f"{sector}&&{cluster}&&cluster&&enabled"] = "0"

        self.set_inputs(inputs)

    def set_bottom_up_site(self, site: str, column_values: dict):
        """
        Set values for a bottom-up site (Shell Pernis, Tata Steel, etc.).
        These use a flat sitename&&column pattern with no sector/cluster prefix.
        """
        inputs = {f"{site}&&enabled": "1"}
        for column, value in column_values.items():
            inputs[f"{site}&&{column}"] = value
        self.set_inputs(inputs)

    # ── Outputs ────────────────────────────────────────────────────────────

    def get_outputs(self, output_ids: list) -> dict:
        """Read one or more output values."""
        data = self._call({
            "SessionID": self.session_id,
            "outputs":   output_ids,
        })
        return data.get("output_values", {})

    def get_all_outputs(self) -> dict:
        """Dump all available output values."""
        data = self._call({
            "SessionID": self.session_id,
            "outputs":   [],
            "special":   ["requestOutputList"],
        })
        return data.get("output_values", {})

    # ── ETM coupling (for later) ───────────────────────────────────────────

    def couple_etm(self, etm_scenario_id: str = None, etm_session_id: str = None,
                   auth_token: str = None):
        """
        Couple the CTM session to an ETM scenario.
        Provide either etm_scenario_id (saved) or etm_session_id (live).
        """
        inputs = {"etm_coupling_switch": "1"}
        if etm_scenario_id:
            inputs["etm_scenario_id"] = etm_scenario_id
        if etm_session_id:
            inputs["etm_session_id"] = etm_session_id
        if auth_token:
            inputs["etm_authorization_token"] = auth_token

        outputs = ["etm_session_id"] if etm_scenario_id else []
        result = self.set_inputs(inputs, outputs=outputs)
        if "etm_session_id" in result:
            print(f"ETM session: {result['etm_session_id']}")
        return result

    def get_available_sites(self) -> dict:
        """
        Returns all sites known to the CTM, grouped by category:
        - 'sector_cluster': regular sites under sector/cluster hierarchy
        - 'bottom_up': large industrial sites (Shell Pernis, Tata Steel etc.)
        - 'custom': ##new_cc_siteN## placeholder slots
        """

        print(f'sesh id: {self.session_id}')
        data = self._call({
            "SessionID": self.session_id,
            "outputs":   [],
            "special":   ["requestFullList"],
        })
        all_keys = data.get("output_values", {}).keys()

        sector_cluster, bottom_up, custom = set(), set(), set()

        for key in all_keys:
            if not key.endswith("&&enabled"):
                continue
            parts = key.split("&&")
            if key.startswith("##new_cc_site"):
                custom.add(parts[0])
            elif len(parts) == 2:
                # sitename&&enabled -> bottom-up
                bottom_up.add(parts[0])
            elif len(parts) == 4:
                # sector&&cluster&&site&&enabled -> regular site
                sector_cluster.add(parts[2])

        return {
            "sector_cluster": sorted(sector_cluster),
            "bottom_up":      sorted(bottom_up),
            "custom":         sorted(custom),
        }

In [2]:
from ctm_client import CTMClient

ctm = CTMClient(use_beta=True)  # switch to True for testing

# ── 1. Create a clean sheet session ───────────────────────────────────────
ctm.create_clean_sheet_session()

try:
    # ── 2a. Sector level ──────────────────────────────────────────────────
    ctm.set_sector(
        sector  = "other_chemicals",
        column  = "natural_gas_demand",
        value   = "3000",
    )

    # ── 2b. Cluster level ─────────────────────────────────────────────────
    ctm.set_cluster(
        sector  = "food",
        cluster = "cluster_6",
        column  = "electricity_demand",
        value   = "500",
    )

    # ── 2c. Regular site level ────────────────────────────────────────────
    ctm.set_site(
        sector  = "food",
        cluster = "cluster_6",
        site    = "heineken_nederland_brouwerij_zoeterwoude",
        column_values = {
            "electricity_demand":  "100",
            "natural_gas_demand":  "200",
        },
    )

    # ── 2d. Bottom-up site ────────────────────────────────────────────────
    ctm.set_bottom_up_site(
        site = "shell_pernis",
        column_values = {
            "electricity_demand":  "2000",
            "natural_gas_demand":  "8000",
        },
    )

    # ── 3. Read outputs ───────────────────────────────────────────────────
    # outputs = ctm.get_outputs(["output_ID_1", "output_ID_2"])
    # print(outputs)
    # outputs = ctm.get_all_outputs()
    # print(list(outputs.keys())[:20])

    # ── 4. Couple to ETM (when ready) ─────────────────────────────────────
    # ctm.couple_etm(etm_scenario_id="1234")


    sites = ctm.get_available_sites()

    print(f"Regular sites: {sites['sector_cluster']}")
    print(f"Bottom-up sites: {len(sites['bottom_up'])}")
    print(f"Custom slots available: {len(sites['custom'])}")

    # Search for a specific plant
    search = "heineken"
    matches = [s for s in sites['sector_cluster'] if search in s.lower()]
    print(f"\nMatches for '{search}': {matches}")

    # print(f'Regular sites: {sites['sector_cluster']}')

finally:
    # always clean up
    # ctm.delete_session()
    print('x')

Session created: SE-ac4d2f07e02f8aec
Clean sheet applied.
sesh id: SE-ac4d2f07e02f8aec
Regular sites: ['a12_cpp_petrogas_ep_netherlands', 'aardgasbuffer_zuidwending', 'abbott_healthcare_products', 'abbott_laboratories', 'adm_europoort', 'agc_flat_glass_nederland', 'agristo', 'alco_energy_rotterdam', 'aluminium_chemie_rotterdam', 'ams05_ams07', 'ams10', 'ams15_de_president', 'ams5', 'ams6', 'ams7', 'ams8', 'amsteldijk_beheer', 'apollo_vredestein', 'ardagh_glass_dongen', 'ardagh_glass_moerdijk', 'asfalt_centrale_bam', 'asfalt_centrale_nijkerk', 'asfalt_centrale_rotterdam', 'asfalt_centrale_utrecht', 'asfalt_productie_amsterdam', 'asfalt_productie_de_eem', 'asfalt_productie_doetinchem', 'asfalt_productie_hoogblokland', 'asfalt_productie_nijmegen', 'asfalt_productie_rasenberg_infra', 'asfalt_productie_rotterdam_rijnmond', 'asfalt_productie_tiel', 'asfalt_productie_westerbroek', 'asfalt_produktie_maatschappij', 'asfaltcentrale_harderwijk_bruil', 'asfaltcentrale_harderwijk_kws', 'asfaltcentrale_heijmans_amsterdam', 'asfaltcentrale_heijmans_s_hertogenbosch', 'asfaltcentrale_heijmans_venlo', 'asfaltcentrale_heijmans_zwijndrecht', 'asfaltcentrale_limburg', 'asfaltcentrale_overbetuwe', 'asfaltcentrale_stedendriehoek', 'asfaltcentrale_twente', 'asfaltproductie_kootstertille', 'asfaltproductie_regio_amsterdam', 'ashland_industries_nederland', 'aspen_oss', 'avebe_ua_foxhol', 'avebe_ua_gasselternijveen', 'avebe_ua_ter_apelkanaal', 'aviko_lomm', 'aviko_steenderen', 'bavaria', 'biopetrol_rotterdam', 'brabantse_asfalt_centrale', 'bunge_loders_croklaan', 'bunge_netherlands_amsterdam', 'bv_steenfabriek_hedikhuizen', 'bv_steenfabriek_huissenswaard', 'bv_steenfabriek_spijk', 'cabot', 'cabot_norit_activated_carbon_klazienaveen_plant', 'caldic_chemie', 'cargill_bergen_op_zoom', 'cargill_multiseed_amsterdam', 'cargill_rotterdam_botlek', 'cargill_sas_van_gent', 'century_aluminum_vlissingen', 'chemours_netherlands', 'climax_molybdenum', 'cluster', 'cluster_site_aluminium_chemelot', 'cluster_site_aluminium_noord_nederland', 'cluster_site_aluminium_nzkg', 'cluster_site_aluminium_rotterdam_moerdijk', 'cluster_site_aluminium_zeeland_west_brabant', 'cluster_site_central_ict_chemelot', 'cluster_site_central_ict_noord_nederland', 'cluster_site_central_ict_nzkg', 'cluster_site_central_ict_rotterdam_moerdijk', 'cluster_site_central_ict_zeeland_west_brabant', 'cluster_site_construction_chemelot', 'cluster_site_construction_noord_nederland', 'cluster_site_construction_nzkg', 'cluster_site_construction_rotterdam_moerdijk', 'cluster_site_construction_zeeland_west_brabant', 'cluster_site_food_chemelot', 'cluster_site_food_noord_nederland', 'cluster_site_food_nzkg', 'cluster_site_food_rotterdam_moerdijk', 'cluster_site_food_zeeland_west_brabant', 'cluster_site_machinery_chemelot', 'cluster_site_machinery_noord_nederland', 'cluster_site_machinery_nzkg', 'cluster_site_machinery_rotterdam_moerdijk', 'cluster_site_machinery_zeeland_west_brabant', 'cluster_site_mining_and_quarrying_chemelot', 'cluster_site_mining_and_quarrying_noord_nederland', 'cluster_site_mining_and_quarrying_nzkg', 'cluster_site_mining_and_quarrying_rotterdam_moerdijk', 'cluster_site_mining_and_quarrying_zeeland_west_brabant', 'cluster_site_non_metallic_minerals_chemelot', 'cluster_site_non_metallic_minerals_noord_nederland', 'cluster_site_non_metallic_minerals_nzkg', 'cluster_site_non_metallic_minerals_rotterdam_moerdijk', 'cluster_site_non_metallic_minerals_zeeland_west_brabant', 'cluster_site_other_chemelot', 'cluster_site_other_chemicals_chemelot', 'cluster_site_other_chemicals_noord_nederland', 'cluster_site_other_chemicals_nzkg', 'cluster_site_other_chemicals_rotterdam_moerdijk', 'cluster_site_other_chemicals_zeeland_west_brabant', 'cluster_site_other_metals_chemelot', 'cluster_site_other_metals_noord_nederland', 'cluster_site_other_metals_nzkg', 'cluster_site_other_metals_rotterdam_moerdijk', 'cluster_site_other_metals_zeeland_west_brabant', 'cluster_site_other_noord_nederland', 'cluster_site_other_nzkg', 'cluster_site_other_rotterdam_moerdijk', 'cluster_site_other_zeeland_west_brabant', 'cluster_site_paper_chemelot', 'cluster_site_paper_noord_nederland', 'cluster_site_paper_nzkg', 'cluster_site_paper_rotterdam_moerdijk', 'cluster_site_paper_zeeland_west_brabant', 'cluster_site_textile_and_leather_chemelot', 'cluster_site_textile_and_leather_noord_nederland', 'cluster_site_textile_and_leather_nzkg', 'cluster_site_textile_and_leather_rotterdam_moerdijk', 'cluster_site_textile_and_leather_zeeland_west_brabant', 'cluster_site_transport_equipment_chemelot', 'cluster_site_transport_equipment_noord_nederland', 'cluster_site_transport_equipment_nzkg', 'cluster_site_transport_equipment_rotterdam_moerdijk', 'cluster_site_transport_equipment_zeeland_west_brabant', 'cluster_site_wood_and_wood_products_chemelot', 'cluster_site_wood_and_wood_products_noord_nederland', 'cluster_site_wood_and_wood_products_nzkg', 'cluster_site_wood_and_wood_products_rotterdam_moerdijk', 'cluster_site_wood_and_wood_products_zeeland_west_brabant', 'coop_grasdrogerij_ruinerwold_en_omstreken_ba', 'croda_nederland', 'crown_van_gelder', 'daf_trucks', 'damco_aluminium_delfzijl_cooperatie_ua', 'dana_petroleum_netherlands_facility_f2_a_hanze', 'dana_petroleum_netherlands_facility_p11_b_de_ruyter', 'danone_nutricia_early_life_nutrition', 'digital_realty_wenckebachweg_127', 'doc_kaas_ba_alteveerstraat', 'doc_kaas_zuivelpark', 'ds_smith_paper_de_hoop_mill', 'dsm_delft_permit', 'e_max_remelt', 'echter_asfaltcentrale', 'edgeconnex_netherlands', 'emerald_kalama_chemical', 'enci_ijmuiden', 'enci_maastricht', 'engie_ep_nederland_d15_a_platform', 'engie_ep_nederland_f3_fb_1_platform', 'engie_ep_nederland_g17_d_a_ap_platform', 'engie_ep_nederland_k12_b_platform', 'engie_ep_nederland_l10_a_platform', 'equinix_am1_am2', 'equinix_am3', 'equinix_am4', 'equinix_am5', 'equinix_am6', 'equinix_am7', 'esd_sic', 'eska_graphic_board_hoogezand', 'eska_graphic_board_sappemeer', 'farm_frites', 'forbo_flooring', 'frieslandcampina_bedum', 'frieslandcampina_beilen', 'frieslandcampina_dmv_veghel', 'frieslandcampina_domo_borculo', 'frieslandcampina_leeuwarden', 'frieslandcampina_lochem', 'frieslandcampina_workum', 'frisia_zout', 'fujifilm_manufacturing_europe', 'gebr_van_der_lee', 'gouda_refractories', 'grasdrogerij_hartog', 'green_box_computing', 'grolsche_bierbrouwerij_nederland', 'haagse_asfaltcentrale', 'heineken_nederland_brouwerij_zoeterwoude', 'heineken_nederland_den_bosch', 'hexion_vondelingenplaat', 'holland_malt_eemshaven', 'hoorn_chevron_expl_and_prod_netherlands', 'huhtamaki_nederland', 'iams_europe', 'indorama_ventures_europe', 'innoviopapers', 'ioi_loders_croklaan_oils', 'jacobs_douwe_egberts_nl', 'jg_timmerman_groeoederdrogerij', 'johnson_matthey', 'kaas_en_weipoederfabriek_a_ware_en_fonterra_h', 'kisuma_chemicals', 'kleiwarenfabriek_buggenum', 'kleiwarenfabriek_de_bylandt', 'kleiwarenfabriek_facade_beek', 'kleiwarenfabriek_joosten_kessel', 'kleiwarenfabriek_joosten_wessem', 'kleiwarenfabriek_nuth', 'koninklijke_mosa_vloertegel', 'koninklijke_mosa_wandtegel', 'koudasfalt_staphorst', 'kws_infra_asfaltcentrale_eindhoven', 'kws_infra_asfaltcentrale_roosendaal', 'lamb_weston_meijer_bergen_op_zoom', 'lamb_weston_meijer_kruiningen', 'mars_food_europe', 'mars_nederland', 'marsna_paper', 'mayr_melnhof_eerbeek', 'mccain_foods_holland_lelystad', 'mccain_foods_holland_lewedorp', 'moerdijk_production_site_basell_benelux', 'monier_tegelen', 'monier_woerden', 'nam_den_helder', 'nam_gasbehandelingsinstallatie_grijpskerk', 'nam_gasproductie_en_gascompressie_installatie', 'nam_gaszuiveringsinstallatie_emmen', 'nam_grijpskerk_usg', 'nam_k14_fa_1c_p', 'nam_l9_ff_1', 'nam_norg_usg', 'nam_warmtekrachtcentrale_en_oliebehandelingsinstallatie_schoonebeek', 'nederlandse_gasunie_cs_alphen', 'nederlandse_gasunie_cs_beverwijk', 'nederlandse_gasunie_cs_oldeboorn', 'nederlandse_gasunie_cs_ravenstein', 'nederlandse_gasunie_cs_spijk', 'nederlandse_gasunie_cs_wieringermeer', 'nederlandse_gasunie_cs_zweekhorst', 'nedmag_mining_and_manufacturing', 'neenah_coldenhove', 'noordelijke_asfaltproductie', 'noordgastransport', 'ntt_global_datacenters_ams1', 'nv_nederlandse_gasunie_lng_maasvlakte', 'nxp_semiconductors_nijmegen', 'nyrstar_budel', 'o_i_manufacturing_netherlands_leerdam', 'o_i_manufacturing_netherlands_maastricht', 'o_i_manufacturing_netherlands_schiedam', 'olam_cocoa', 'oldambt_groeoederdrogerij', 'ooms_producten', 'owens_corning_veil_netherlands', 'papierfabriek_doetinchem', 'parenco', 'peka_kroef', 'pepsico_nederland', 'pgi_nonwovens', 'philip_morris_holland', 'platform_j6_a', 'ppg_industries_chemicals', 'ppg_industries_fiber_glass', 'pq_silicas', 'promelca_dairy_foods', 'purac_biochem', 'rendac_son', 'rixona', 'rockwool', 'rodruza_steenfabriek_rossum', 'rodruza_steenfabriek_zandberg', 'sabic_innovative_plastics', 'saint_gobain_construction_products_nederland', 'sappi_maastricht', 'sca_hygiene_products_cuijk', 'sector_site_aluminium', 'sector_site_central_ict', 'sector_site_construction', 'sector_site_food', 'sector_site_machinery', 'sector_site_mining_and_quarrying', 'sector_site_non_metallic_minerals', 'sector_site_other', 'sector_site_other_chemicals', 'sector_site_other_metals', 'sector_site_paper', 'sector_site_textile_and_leather', 'sector_site_transport_equipment', 'sector_site_wood_and_wood_products', 'sensus_roosendaal', 'sensus_zwolle', 'shin_etsu_pvc_botlek', 'sime_darby_unimills', 'siniat', 'smart_packaging_solutions', 'smurfit_kappa_roermond_papier', 'solidus_solutions_board_coevorden', 'solidus_solutions_board_hoogkerk', 'solidus_solutions_board_loc_bad_nieuweschans', 'solidus_solutions_board_oude_pekela', 'sonac_burgum', 'sonac_vuren', 'sonneborn_refined_products', 'steenfabriek_de_rijswaard', 'steenfabriek_engels_helden', 'steenfabriek_engels_oeffelt', 'steenfabriek_gebroeders_klinkers', 'steenfabriek_linssen', 'steenindustrie_strating', 'steinzeug_keramo', 'strabag_asfalt', 'suiker_unie_dinteloord', 'suiker_unie_vierverlaten', 'synthomer', 'taqa_offshore', 'taqa_onshore', 'taqa_piekgas', 'tate_lyle_netherlands', 'ten_cate_advanced_textiles', 'tencate_outdoor_fabrics', 'total_offshore_platform_f15a', 'total_offshore_platform_k5_central_complex', 'total_offshore_platform_k6_central_complex', 'total_offshore_platform_l7_central_complex', 'trespa_international', 'van_houtum', 'vdl_nedcar', 'vlisco_netherlands', 'wienerberger_dakpannenfabriek_janssen_dings', 'wienerberger_dakpannenfabriek_narvik_deest', 'wienerberger_dakpannenfabriek_narvik_tegelen', 'wienerberger_steenfabriek_bemmel', 'wienerberger_steenfabriek_de_nijverheid', 'wienerberger_steenfabriek_de_vlijt', 'wienerberger_steenfabriek_erlecom', 'wienerberger_steenfabriek_haaften', 'wienerberger_steenfabriek_heteren', 'wienerberger_steenfabriek_kijfwaard_oost', 'wienerberger_steenfabriek_kijfwaard_west', 'wienerberger_steenfabriek_nuance', 'wienerberger_steenfabriek_poriso', 'wienerberger_steenfabriek_schipperswaard', 'wienerberger_steenfabriek_thorn', 'wienerberger_steenfabriek_wolfswaard', 'wienerberger_steenfabriek_zennewijnen', 'wintershall_noordzee_f16_a', 'wintershall_noordzee_l8_p4', 'wintershall_noordzee_p6_a', 'zalco', 'zwanenberg_food_oss']
Bottom-up sites: 26
Custom slots available: 234

Matches for 'heineken': ['heineken_nederland_brouwerij_zoeterwoude', 'heineken_nederland_den_bosch']
x

In [3]:
print(ctm.session_id)

SE-ac4d2f07e02f8aec

In [22]:
# dump everything for one site and see what fields exist
all_data = ctm._call({
    "SessionID": ctm.session_id,
    "outputs": [],
    "special": ["requestFullList"],
}).get("output_values", {})

# pick any known site and see all its keys
site = "cargill_bergen"
site_keys = {k: v for k, v in all_data.items() if site in k}
print(site_keys)

HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://beta.carbontransitionmodel.com/api/

In [5]:
import polars as pl
df = pl.DataFrame(
    {
        "key": list(site_keys.keys()),
        "value": list(site_keys.values()),
    },
    strict=False
)

df

shape: (813, 2)
┌─────────────────────────────────┬───────┐
│ key                             ┆ value │
│ ---                             ┆ ---   │
│ str                             ┆ str   │
╞═════════════════════════════════╪═══════╡
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ …                               ┆ …     │
│ site_shell_moerdijk_waste_gas_… ┆ n/a   │
│ site_shell_moerdijk_waste_gas_… ┆ 0     │
│ site_shell_moerdijk_waste_gas_… ┆ n/a   │
│ tech_sector_shell_moerdijk_dow… ┆ 0.387 │
│ tech_sector_shell_moerdijk_dow… ┆ 3.246 │
└─────────────────────────────────┴───────┘

In [6]:
aux = df.filter(pl.col('key').str.contains('gas'))
aux

shape: (90, 2)
┌─────────────────────────────────┬───────┐
│ key                             ┆ value │
│ ---                             ┆ ---   │
│ str                             ┆ str   │
╞═════════════════════════════════╪═══════╡
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ …                               ┆ …     │
│ site_shell_moerdijk_waste_gas_… ┆ n/a   │
│ site_shell_moerdijk_waste_gas_… ┆ 0     │
│ site_shell_moerdijk_waste_gas_… ┆ n/a   │
│ site_shell_moerdijk_waste_gas_… ┆ 0     │
│ site_shell_moerdijk_waste_gas_… ┆ n/a   │
└─────────────────────────────────┴───────┘

In [7]:
auxx = aux.filter(pl.col('key').str.contains('heat'))
auxx

shape: (6, 2)
┌─────────────────────────────────┬───────┐
│ key                             ┆ value │
│ ---                             ┆ ---   │
│ str                             ┆ str   │
╞═════════════════════════════════╪═══════╡
│ shell_moerdijk_heat_integratio… ┆ 242.3 │
│ shell_moerdijk_heat_integratio… ┆ 1     │
│ shell_moerdijk_heat_integratio… ┆ 0.7   │
│ site_shell_moerdijk_etm_heat_g… ┆ n/a   │
│ site_shell_moerdijk_heat_gasbo… ┆ n/a   │
│ site_shell_moerdijk_heat_gasbo… ┆ n/a   │
└─────────────────────────────────┴───────┘

In [8]:
aux2 = df.with_columns(
    pl.col("key")
      .str.split("&&")
      .list.get(0)
      .alias("sector")
).filter(pl.col('sector').is_in(SECTORS)).with_columns(pl.col("key")
      .str.split("&&")
      .list.get(1)
      .alias("cluster")).filter(pl.col('cluster').is_in(CLUSTERS))
aux2

shape: (0, 4)
┌─────┬───────┬────────┬─────────┐
│ key ┆ value ┆ sector ┆ cluster │
│ --- ┆ ---   ┆ ---    ┆ ---     │
│ str ┆ str   ┆ str    ┆ str     │
╞═════╪═══════╪════════╪═════════╡
└─────┴───────┴────────┴─────────┘

In [9]:
aux3 = aux2.with_columns(
    pl.col("key")
      .str.split("&&")
      .list.get(2)
      .alias("plant")
).filter((~pl.col('plant').is_in(FIELDS)) & (~pl.col('plant').str.contains('cluster')) & (~pl.col('plant').str.contains('residue')))
plantsss = aux3.select('plant').unique()
plantsss

shape: (0, 1)
┌───────┐
│ plant │
│ ---   │
│ str   │
╞═══════╡
└───────┘

In [10]:
import polars as pl
plants = pl.read_csv('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/dsh/20260508_new/datasafehouse-plant-export.csv.csv')

In [11]:
plants = plants.with_columns(pl.col("Plant name")
    .str.to_lowercase()
    .str.replace_all(" ", "_")
    .alias("Plant name updated"))

plants

shape: (93, 13)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Latitude  ┆ Longitude ┆ Address   ┆ Zip code ┆ … ┆ Existing  ┆ KvK       ┆ All EANs  ┆ Plant     │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ plant/New ┆ number(s) ┆ ---       ┆ name      │
│ f64       ┆ f64       ┆ str       ┆ str      ┆   ┆ plant     ┆ ---       ┆ str       ┆ updated   │
│           ┆           ┆           ┆          ┆   ┆ ---       ┆ i64       ┆           ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆ str       ┆           ┆           ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 51.956512 ┆ 4.122673  ┆ Elbeweg   ┆ 3198LC   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ adm_europ │
│           ┆           ┆ 125       ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ oort      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 892760000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 783…      ┆           │
│ 52.40095  ┆ 4.792595  ┆ australie ┆ 1045BA   ┆ … ┆ existing  ┆ 58867937  ┆ [{"ean_co ┆ aeb_-_aec │
│           ┆           ┆ havenweg  ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ _/_hrc    │
│           ┆           ┆ 21        ┆          ┆   ┆           ┆           ┆ 859000000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 026…      ┆           │
│ 52.405947 ┆ 4.85313   ┆ Petroleum ┆ 1041AB   ┆ … ┆ existing  ┆ 58867937  ┆ [{"ean_co ┆ aeb_-_bec │
│           ┆           ┆ havenweg  ┆          ┆   ┆           ┆           ┆ de":"8716 ┆           │
│           ┆           ┆ 1B        ┆          ┆   ┆           ┆           ┆ 859200033 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 329…      ┆           │
│ 51.50933  ┆ 4.255797  ┆ Plasticsl ┆ 4600AC   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ air_liqui │
│           ┆           ┆ aan 1     ┆          ┆   ┆           ┆           ┆ de":"8717 ┆ de_bergen │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 185180030 ┆ _op_zoom  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 155…      ┆           │
│ null      ┆ null      ┆ Keteldiep ┆ 4791SM   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ air_liqui │
│           ┆           ┆ 1C        ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ de_booste │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 879100004 ┆ r_moerdij │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 675…      ┆ k         │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 51.910616 ┆ 4.217811  ┆ Neckarweg ┆ 3198LJ   ┆ … ┆ existing  ┆ 33298434  ┆ [{"ean_co ┆ vpr_europ │
│           ┆           ┆ 5         ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ oort      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 892760000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 022…      ┆           │
│ 52.461595 ┆ 4.586851  ┆ Halkade 4 ┆ 1976DC   ┆ … ┆ new       ┆ 34065340  ┆ [{"ean_co ┆ walstroom │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ de":null, ┆ _halkade  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ "grid_ope ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ rat…      ┆           │
│ 52.459608 ┆ 4.569951  ┆ Monnicken ┆ 1976DC   ┆ … ┆ new       ┆ 34065340  ┆ [{"ean_co ┆ walstroom │
│           ┆           ┆ damkade   ┆          ┆   ┆           ┆           ┆ de":null, ┆ _monnicke │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ "grid_ope ┆ ndamkade  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ rat…      ┆           │
│ 51.275734 ┆ 3.851941  ┆ Industrie ┆ 4541HJ   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ yara_slui │
│           ┆           ┆ weg 10    ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ skil      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 867000000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 255…      ┆           │
│ 51.449263 ┆ 3.727321  ┆ Luxemburg ┆ 4455TM   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ zeeland_r │
│           ┆           ┆ weg 1     ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ efinery   │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 902000000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 004…      ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
aux3

shape: (0, 5)
┌─────┬───────┬────────┬─────────┬───────┐
│ key ┆ value ┆ sector ┆ cluster ┆ plant │
│ --- ┆ ---   ┆ ---    ┆ ---     ┆ ---   │
│ str ┆ str   ┆ str    ┆ str     ┆ str   │
╞═════╪═══════╪════════╪═════════╪═══════╡
└─────┴───────┴────────┴─────────┴───────┘

In [13]:

fields_split = {
    'Plant name': 'location',
    'Address':    'adress',     #food&&zeeland_west_brabant&&cargill_bergen_op_zoom&&adress
    'ZIP':        'zip_code',
    'City':       'city',
}

fields_suffix = {
    'Latitude':  'latitude_dashboard',  #site_cargill_bergen_op_zoom_latitude_dashboard
    'Longitude': 'longitude_dashboard',
}

another = (
    aux3
    .with_columns(field=pl.col("key").str.split("&&").list.get(-1))
    .with_columns(
        *[
            pl.when(pl.col("field") == field)
            .then(pl.col("value"))
            .alias(col)
            for col, field in fields_split.items()
        ],
        *[
            pl.when(pl.col("key").str.ends_with(suffix))
            .then(pl.col("value"))
            .alias(col)
            for col, suffix in fields_suffix.items()
        ],
    )
)
another

shape: (0, 12)
┌─────┬───────┬────────┬─────────┬───┬─────┬──────┬──────────┬───────────┐
│ key ┆ value ┆ sector ┆ cluster ┆ … ┆ ZIP ┆ City ┆ Latitude ┆ Longitude │
│ --- ┆ ---   ┆ ---    ┆ ---     ┆   ┆ --- ┆ ---  ┆ ---      ┆ ---       │
│ str ┆ str   ┆ str    ┆ str     ┆   ┆ str ┆ str  ┆ str      ┆ str       │
╞═════╪═══════╪════════╪═════════╪═══╪═════╪══════╪══════════╪═══════════╡
└─────┴───────┴────────┴─────────┴───┴─────┴──────┴──────────┴───────────┘

In [14]:
fin = (
    another
    .group_by(["sector", "cluster", "plant"])
    .agg(
        pl.col("Plant name").drop_nulls().first(),
        pl.col("Address").drop_nulls().first(),
        pl.col("Latitude").drop_nulls().first(),
        pl.col("Longitude").drop_nulls().first(),
        pl.col("ZIP").drop_nulls().first(),
        pl.col("City").drop_nulls().first(),
    )
)

fin

shape: (0, 9)
┌────────┬─────────┬───────┬────────────┬───┬──────────┬───────────┬─────┬──────┐
│ sector ┆ cluster ┆ plant ┆ Plant name ┆ … ┆ Latitude ┆ Longitude ┆ ZIP ┆ City │
│ ---    ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---      ┆ ---       ┆ --- ┆ ---  │
│ str    ┆ str     ┆ str   ┆ str        ┆   ┆ str      ┆ str       ┆ str ┆ str  │
╞════════╪═════════╪═══════╪════════════╪═══╪══════════╪═══════════╪═════╪══════╡
└────────┴─────────┴───────┴────────────┴───┴──────────┴───────────┴─────┴──────┘

In [15]:
aux3

shape: (0, 5)
┌─────┬───────┬────────┬─────────┬───────┐
│ key ┆ value ┆ sector ┆ cluster ┆ plant │
│ --- ┆ ---   ┆ ---    ┆ ---     ┆ ---   │
│ str ┆ str   ┆ str    ┆ str     ┆ str   │
╞═════╪═══════╪════════╪═════════╪═══════╡
└─────┴───────┴────────┴─────────┴───────┘

In [16]:
aux4 = aux3.select(['sector', 'cluster', 'plant']).unique()
aux4

shape: (0, 3)
┌────────┬─────────┬───────┐
│ sector ┆ cluster ┆ plant │
│ ---    ┆ ---     ┆ ---   │
│ str    ┆ str     ┆ str   │
╞════════╪═════════╪═══════╡
└────────┴─────────┴───────┘

In [17]:
joined =aux4.join(plants,
              left_on='plant',
              right_on='Plant name updated',
              how='inner')

joined

shape: (0, 15)
┌────────┬─────────┬───────┬──────────┬───┬────────────┬───────────┬───────────────┬──────────┐
│ sector ┆ cluster ┆ plant ┆ Latitude ┆ … ┆ Plant      ┆ Existing  ┆ KvK number(s) ┆ All EANs │
│ ---    ┆ ---     ┆ ---   ┆ ---      ┆   ┆ identifier ┆ plant/New ┆ ---           ┆ ---      │
│ str    ┆ str     ┆ str   ┆ f64      ┆   ┆ ---        ┆ plant     ┆ i64           ┆ str      │
│        ┆         ┆       ┆          ┆   ┆ str        ┆ ---       ┆               ┆          │
│        ┆         ┆       ┆          ┆   ┆            ┆ str       ┆               ┆          │
╞════════╪═════════╪═══════╪══════════╪═══╪════════════╪═══════════╪═══════════════╪══════════╡
└────────┴─────────┴───────┴──────────┴───┴────────────┴───────────┴───────────────┴──────────┘

In [18]:
plants

shape: (93, 13)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Latitude  ┆ Longitude ┆ Address   ┆ Zip code ┆ … ┆ Existing  ┆ KvK       ┆ All EANs  ┆ Plant     │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ plant/New ┆ number(s) ┆ ---       ┆ name      │
│ f64       ┆ f64       ┆ str       ┆ str      ┆   ┆ plant     ┆ ---       ┆ str       ┆ updated   │
│           ┆           ┆           ┆          ┆   ┆ ---       ┆ i64       ┆           ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆ str       ┆           ┆           ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 51.956512 ┆ 4.122673  ┆ Elbeweg   ┆ 3198LC   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ adm_europ │
│           ┆           ┆ 125       ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ oort      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 892760000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 783…      ┆           │
│ 52.40095  ┆ 4.792595  ┆ australie ┆ 1045BA   ┆ … ┆ existing  ┆ 58867937  ┆ [{"ean_co ┆ aeb_-_aec │
│           ┆           ┆ havenweg  ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ _/_hrc    │
│           ┆           ┆ 21        ┆          ┆   ┆           ┆           ┆ 859000000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 026…      ┆           │
│ 52.405947 ┆ 4.85313   ┆ Petroleum ┆ 1041AB   ┆ … ┆ existing  ┆ 58867937  ┆ [{"ean_co ┆ aeb_-_bec │
│           ┆           ┆ havenweg  ┆          ┆   ┆           ┆           ┆ de":"8716 ┆           │
│           ┆           ┆ 1B        ┆          ┆   ┆           ┆           ┆ 859200033 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 329…      ┆           │
│ 51.50933  ┆ 4.255797  ┆ Plasticsl ┆ 4600AC   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ air_liqui │
│           ┆           ┆ aan 1     ┆          ┆   ┆           ┆           ┆ de":"8717 ┆ de_bergen │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 185180030 ┆ _op_zoom  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 155…      ┆           │
│ null      ┆ null      ┆ Keteldiep ┆ 4791SM   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ air_liqui │
│           ┆           ┆ 1C        ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ de_booste │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 879100004 ┆ r_moerdij │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 675…      ┆ k         │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 51.910616 ┆ 4.217811  ┆ Neckarweg ┆ 3198LJ   ┆ … ┆ existing  ┆ 33298434  ┆ [{"ean_co ┆ vpr_europ │
│           ┆           ┆ 5         ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ oort      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 892760000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 022…      ┆           │
│ 52.461595 ┆ 4.586851  ┆ Halkade 4 ┆ 1976DC   ┆ … ┆ new       ┆ 34065340  ┆ [{"ean_co ┆ walstroom │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ de":null, ┆ _halkade  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ "grid_ope ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ rat…      ┆           │
│ 52.459608 ┆ 4.569951  ┆ Monnicken ┆ 1976DC   ┆ … ┆ new       ┆ 34065340  ┆ [{"ean_co ┆ walstroom │
│           ┆           ┆ damkade   ┆          ┆   ┆           ┆           ┆ de":null, ┆ _monnicke │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ "grid_ope ┆ ndamkade  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ rat…      ┆           │
│ 51.275734 ┆ 3.851941  ┆ Industrie ┆ 4541HJ   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ yara_slui │
│           ┆           ┆ weg 10    ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ skil      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 867000000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 255…      ┆           │
│ 51.449263 ┆ 3.727321  ┆ Luxemburg ┆ 4455TM   ┆ … ┆ existing  ┆ null      ┆ [{"ean_co ┆ zeeland_r │
│           ┆           ┆ weg 1     ┆          ┆   ┆           ┆           ┆ de":"8716 ┆ efinery   │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 902000000 ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 004…      ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
joined2 =fin.join(plants.select(['Latitude', 'Longitude', 'Address', 'Zip code', 'City', 'Plant name']),
              left_on='Plant name',
              right_on='Plant name',
              how='inner')

joined2

shape: (0, 14)
┌────────┬─────────┬───────┬────────────┬───┬───────────────┬──────────────┬──────────┬────────────┐
│ sector ┆ cluster ┆ plant ┆ Plant name ┆ … ┆ Longitude_rig ┆ Address_righ ┆ Zip code ┆ City_right │
│ ---    ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ht            ┆ t            ┆ ---      ┆ ---        │
│ str    ┆ str     ┆ str   ┆ str        ┆   ┆ ---           ┆ ---          ┆ str      ┆ str        │
│        ┆         ┆       ┆            ┆   ┆ f64           ┆ str          ┆          ┆            │
╞════════╪═════════╪═══════╪════════════╪═══╪═══════════════╪══════════════╪══════════╪════════════╡
└────────┴─────────┴───────┴────────────┴───┴───────────────┴──────────────┴──────────┴────────────┘

### What?

In [20]:
df.filter(~pl.col('key').str.contains('new_cc_site'))

shape: (813, 2)
┌─────────────────────────────────┬───────┐
│ key                             ┆ value │
│ ---                             ┆ ---   │
│ str                             ┆ str   │
╞═════════════════════════════════╪═══════╡
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ ldsh&&other_chemicals&&rotterd… ┆       │
│ …                               ┆ …     │
│ site_shell_moerdijk_waste_gas_… ┆ n/a   │
│ site_shell_moerdijk_waste_gas_… ┆ 0     │
│ site_shell_moerdijk_waste_gas_… ┆ n/a   │
│ tech_sector_shell_moerdijk_dow… ┆ 0.387 │
│ tech_sector_shell_moerdijk_dow… ┆ 3.246 │
└─────────────────────────────────┴───────┘

In [21]:
# ctm.delete_session()