In [1]:
import polars as pl
import pandas as pd

In [2]:
SCENARIO_NAMES_DICT = {
    1: 'Midden',
    2: 'VT',
    3: 'Elektrificatie',
    4: 'Waterstof',
    5: 'Groen gas'
}

REFERENCE_YEAR = '2024'

In [3]:
scenario = SCENARIO_NAMES_DICT[1]
print(scenario)

Midden

In [4]:
test_file_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/Shell Chemie Moerdijk.xlsx'

In [5]:
x = pl.read_excel('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/Shell Chemie Moerdijk.xlsx',
              sheet_name=f'Scenario {scenario}')

In [45]:
import polars as pl
from openpyxl import load_workbook



def read_scenario_sheet(
    workbook_path: str,
    sheet_name: str,
    emission_cols: list[str],
    energy_cols: list[str],
    reference_year: int,
) -> pl.DataFrame:
    """
    Read a Scenario X sheet created by write_scenario_sheets().

    Returns a normalized dataframe with:
        Strategy
        Year
        Flow type
        <emission cols>
        <energy cols>

    - Skips the reference year
    - Handles merged year cells
    - Keeps rows even if all values are blank
    - Ignores separator rows
    """

    wb = load_workbook(workbook_path, data_only=True)
    ws = wb[sheet_name]

    scenario = sheet_name.replace("Scenario ", "")

    records = []
    current_year = None

    emission_start = 4
    energy_start = emission_start + len(emission_cols)

    for row_idx in range(5, ws.max_row + 1):

        # Year column (merged vertically)
        year_cell = ws.cell(row_idx, 2).value
        if year_cell is not None:
            current_year = str(year_cell)

        # Flow type column
        flow_type = ws.cell(row_idx, 3).value

        # Skip separator rows
        if flow_type is None:
            continue

        # Skip reference year
        if current_year == str(reference_year):
            continue

        record = {
            "Scenario": scenario,
            "Year": current_year,
            "Flow type": str(flow_type).lower(),
        }

        # Emissions
        for i, col in enumerate(emission_cols):
            record[col] = ws.cell(
                row_idx,
                emission_start + i
            ).value

        # Energy
        for i, col in enumerate(energy_cols):
            record[col] = ws.cell(
                row_idx,
                energy_start + i
            ).value

        # Keep row even if all values are empty
        records.append(record)

    if not records:
        return pl.DataFrame(
            schema={
                "Scenario": pl.Utf8,
                "Year": pl.Utf8,
                "Flow type": pl.Utf8,
                **{c: pl.Float64 for c in emission_cols},
                **{c: pl.Float64 for c in energy_cols},
            }
        )

    return pl.DataFrame(records)

In [46]:
STRICT_EMISSIONS_ORDER = ["CO2", "Methane", "N2O", "F-gases"]
EMISSION_COLS_ORDER =  STRICT_EMISSIONS_ORDER + ["CO2 (fossil) CCU/CCS", "CO2 (bio) CCU/CCS"]#, "other"]

# Single source of truth — used in both energy balance and project sheets
UTILITY_COLS_ORDER = [
    'Electricity',
    'Electricity_peak',
    'Natural Gas',
    'Hydrogen ( >98% vol.%) (LHV)',
    'Hydrogen ( <98% vol.%) (LHV)',
    'Heat',
    'Residual gases',
    'Coal and coal products',
    'Oil and oil products',
    'Biomass (liquid)',
    'Biomass (solid)',
    'Green gas',
    'Waste (fossil)',
    'Waste (bio)',
    'Ammonia',
    'Methanol',
    'Other syn fuel and raw materials',
    'Other',
]

In [48]:
df = read_scenario_sheet(
    test_file_path,
    f'Scenario {scenario}',
    EMISSION_COLS_ORDER,
    UTILITY_COLS_ORDER,
    REFERENCE_YEAR
)

In [49]:
df

shape: (16, 27)
┌──────────┬──────┬─────────────┬──────┬───┬─────────┬──────────┬──────────────────────────┬───────┐
│ Scenario ┆ Year ┆ Flow type   ┆ CO2  ┆ … ┆ Ammonia ┆ Methanol ┆ Other syn fuel and raw   ┆ Other │
│ ---      ┆ ---  ┆ ---         ┆ ---  ┆   ┆ ---     ┆ ---      ┆ materia…                 ┆ ---   │
│ str      ┆ str  ┆ str         ┆ i64  ┆   ┆ null    ┆ null     ┆ ---                      ┆ null  │
│          ┆      ┆             ┆      ┆   ┆         ┆          ┆ null                     ┆       │
╞══════════╪══════╪═════════════╪══════╪═══╪═════════╪══════════╪══════════════════════════╪═══════╡
│ Midden   ┆ 2030 ┆ demand      ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2030 ┆ captive use ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2030 ┆ production  ┆ 1758 ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2030 ┆ supply      ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2035 ┆ demand      ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ …        ┆ …    ┆ …           ┆ …    ┆ … ┆ …       ┆ …        ┆ …                        ┆ …     │
│ Midden   ┆ 2040 ┆ supply      ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2050 ┆ demand      ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2050 ┆ captive use ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2050 ┆ production  ┆ 1379 ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden   ┆ 2050 ┆ supply      ┆ null ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
└──────────┴──────┴─────────────┴──────┴───┴─────────┴──────────┴──────────────────────────┴───────┘

In [10]:
prod = pl.read_excel('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/Shell Chemie Moerdijk.xlsx',
              sheet_name=f'Production')

Could not determine dtype for column 11, falling back to string

In [11]:
prod

shape: (7, 19)
┌─────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────┬────────────┐
│ Name        ┆ Year ┆ Status     ┆ Production ┆ … ┆ Must run   ┆ Must run   ┆ Is CHP ┆ CHP heat   │
│ ---         ┆ ---  ┆ ---        ┆ type       ┆   ┆ period     ┆ power (%)  ┆ ---    ┆ efficiency │
│ str         ┆ str  ┆ str        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ bool   ┆ (%)        │
│             ┆      ┆            ┆ str        ┆   ┆ str        ┆ str        ┆        ┆ ---        │
│             ┆      ┆            ┆            ┆   ┆            ┆            ┆        ┆ i64        │
╞═════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════╪════════════╡
│ Shell       ┆ 2023 ┆ Operationa ┆ Solar phot ┆ … ┆ null       ┆ null       ┆ false  ┆ null       │
│ Chemie      ┆      ┆ l          ┆ ovoltaic   ┆   ┆            ┆            ┆        ┆            │
│ Moerdijk    ┆      ┆            ┆ energy     ┆   ┆            ┆            ┆        ┆            │
│ Shell       ┆ 2023 ┆ Operationa ┆ Thermal    ┆ … ┆ All year   ┆ 92         ┆ true   ┆ 90         │
│ Chemie      ┆      ┆ l          ┆ unit       ┆   ┆            ┆            ┆        ┆            │
│ Moerdijk    ┆      ┆            ┆            ┆   ┆            ┆            ┆        ┆            │
│ Scenario    ┆ Year ┆ Capacity   ┆ FLH        ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│ Midden      ┆ 2030 ┆ 37         ┆ 7000       ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│ Midden      ┆ 2035 ┆ 37         ┆ 7000       ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│ Midden      ┆ 2040 ┆ 37         ┆ 7000       ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│ Midden      ┆ 2050 ┆ 0          ┆ 0          ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
└─────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────┴────────────┘

In [12]:
import polars as pl


def read_production_table(
    workbook_path: str,
    sheet_name: str = "Production",
) -> pl.DataFrame:
    # Read entire sheet without assuming a header
    raw = pl.read_excel(
        workbook_path,
        sheet_name=sheet_name,
        has_header=False,
    )

    # Find row containing the table header
    header_row = (
        raw.with_row_index()
        .filter(
            (pl.col("column_1") == "Scenario")
            & (pl.col("column_2") == "Year")
        )
        .select("index")
        .item()
    )

    # Extract header values
    header_values = raw.row(header_row)

    # Keep columns until first null header
    n_cols = next(
        (i for i, v in enumerate(header_values) if v is None),
        len(header_values)
    )

    headers = [str(v) for v in header_values[:n_cols]]

    # Data below header
    data = raw.slice(header_row + 1)

    # Keep only relevant columns
    data = data.select(data.columns[:n_cols])

    # Rename columns
    data.columns = headers

    # Stop at first completely empty row
    empty_mask = pl.all_horizontal(
        [pl.col(c).is_null() for c in data.columns]
    )

    empty_rows = (
        data.with_row_index()
        .filter(empty_mask)
        .select("index")
        .to_series()
        .to_list()
    )

    if empty_rows:
        data = data.slice(0, empty_rows[0])

    return data

In [13]:
production = read_production_table(test_file_path)

In [14]:
production

shape: (4, 5)
┌──────────┬──────┬──────────┬──────┬────────────┐
│ Scenario ┆ Year ┆ Capacity ┆ FLH  ┆ Efficiency │
│ ---      ┆ ---  ┆ ---      ┆ ---  ┆ ---        │
│ str      ┆ str  ┆ str      ┆ str  ┆ str        │
╞══════════╪══════╪══════════╪══════╪════════════╡
│ Midden   ┆ 2030 ┆ 37       ┆ 7000 ┆ 31         │
│ Midden   ┆ 2035 ┆ 37       ┆ 7000 ┆ 31         │
│ Midden   ┆ 2040 ┆ 37       ┆ 7000 ┆ 31         │
│ Midden   ┆ 2050 ┆ 0        ┆ 0    ┆ 31         │
└──────────┴──────┴──────────┴──────┴────────────┘

In [59]:
def aggregate_scenarios_flow_types(all_df: pl.DataFrame) -> pl.DataFrame:

    value_cols = [c for c in all_df.columns if c not in ('Scenario', 'Year', 'Flow type')]

    production = all_df.filter(pl.col('Flow type') == 'production')

    demand = (
        all_df.filter(pl.col('Flow type').is_in(['demand', 'captive use']))
        .group_by(['Scenario', 'Year'])
        .agg([pl.col(c).sum() for c in value_cols])
        .with_columns(pl.lit('demand').alias('Flow type'))
        .select(all_df.columns)  # restore original column order
    )

    result = pl.concat([production, demand])
    return result


def read_all_scenario_sheets(
    workbook_path: str,
    emission_cols: list[str],
    energy_cols: list[str],
    reference_year: int,
    aggregate_flow_types:bool = True
) -> pl.DataFrame:
    """
    Read all Scenario X sheets and return a single dataframe.
    """

    wb = load_workbook(workbook_path, read_only=True)

    scenario_sheets = [
        sheet
        for sheet in wb.sheetnames
        if sheet.startswith("Scenario ")
    ]

    dfs = [
        read_scenario_sheet(
            workbook_path=workbook_path,
            sheet_name=sheet,
            emission_cols=emission_cols,
            energy_cols=energy_cols,
            reference_year=reference_year,
        )
        for sheet in scenario_sheets
    ]

    if not dfs:
        return pl.DataFrame()
    
    if aggregate_flow_types:
        all_df = pl.concat(dfs, how="vertical_relaxed")
        return aggregate_scenarios_flow_types(all_df)

    return pl.concat(dfs, how="vertical_relaxed")

In [60]:
all_df = read_all_scenario_sheets(test_file_path, 
                                  emission_cols=EMISSION_COLS_ORDER, 
                                  energy_cols=UTILITY_COLS_ORDER, 
                                  reference_year=REFERENCE_YEAR)

In [61]:
all_df

shape: (40, 27)
┌───────────┬──────┬────────────┬──────┬───┬─────────┬──────────┬──────────────────────────┬───────┐
│ Scenario  ┆ Year ┆ Flow type  ┆ CO2  ┆ … ┆ Ammonia ┆ Methanol ┆ Other syn fuel and raw   ┆ Other │
│ ---       ┆ ---  ┆ ---        ┆ ---  ┆   ┆ ---     ┆ ---      ┆ materia…                 ┆ ---   │
│ str       ┆ str  ┆ str        ┆ i64  ┆   ┆ null    ┆ null     ┆ ---                      ┆ null  │
│           ┆      ┆            ┆      ┆   ┆         ┆          ┆ null                     ┆       │
╞═══════════╪══════╪════════════╪══════╪═══╪═════════╪══════════╪══════════════════════════╪═══════╡
│ Midden    ┆ 2030 ┆ production ┆ 1758 ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden    ┆ 2035 ┆ production ┆ 1379 ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden    ┆ 2040 ┆ production ┆ 1379 ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden    ┆ 2050 ┆ production ┆ 1379 ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ VT        ┆ 2030 ┆ production ┆ 1758 ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ …         ┆ …    ┆ …          ┆ …    ┆ … ┆ …       ┆ …        ┆ …                        ┆ …     │
│ Midden    ┆ 2040 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Waterstof ┆ 2035 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Waterstof ┆ 2040 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Waterstof ┆ 2030 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
│ Midden    ┆ 2030 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                     ┆ null  │
└───────────┴──────┴────────────┴──────┴───┴─────────┴──────────┴──────────────────────────┴───────┘

In [57]:
value_cols = [c for c in all_df.columns if c not in ('Scenario', 'Year', 'Flow type')]

production = all_df.filter(pl.col('Flow type') == 'production')

demand = (
    all_df.filter(pl.col('Flow type').is_in(['demand', 'captive use']))
      .group_by(['Scenario', 'Year'])
      .agg([pl.col(c).sum() for c in value_cols])
      .with_columns(pl.lit('demand').alias('Flow type'))
      .select(all_df.columns)  # restore original column order
)

result = pl.concat([production, demand])
result

shape: (40, 27)
┌────────────────┬──────┬────────────┬──────┬───┬─────────┬──────────┬─────────────────────┬───────┐
│ Scenario       ┆ Year ┆ Flow type  ┆ CO2  ┆ … ┆ Ammonia ┆ Methanol ┆ Other syn fuel and  ┆ Other │
│ ---            ┆ ---  ┆ ---        ┆ ---  ┆   ┆ ---     ┆ ---      ┆ raw materia…        ┆ ---   │
│ str            ┆ str  ┆ str        ┆ i64  ┆   ┆ null    ┆ null     ┆ ---                 ┆ null  │
│                ┆      ┆            ┆      ┆   ┆         ┆          ┆ null                ┆       │
╞════════════════╪══════╪════════════╪══════╪═══╪═════════╪══════════╪═════════════════════╪═══════╡
│ Midden         ┆ 2030 ┆ production ┆ 1758 ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ Midden         ┆ 2035 ┆ production ┆ 1379 ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ Midden         ┆ 2040 ┆ production ┆ 1379 ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ Midden         ┆ 2050 ┆ production ┆ 1379 ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ VT             ┆ 2030 ┆ production ┆ 1758 ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ …              ┆ …    ┆ …          ┆ …    ┆ … ┆ …       ┆ …        ┆ …                   ┆ …     │
│ Groen gas      ┆ 2040 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ Groen gas      ┆ 2050 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ Midden         ┆ 2050 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ Groen gas      ┆ 2035 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
│ Elektrificatie ┆ 2040 ┆ demand     ┆ 0    ┆ … ┆ null    ┆ null     ┆ null                ┆ null  │
└────────────────┴──────┴────────────┴──────┴───┴─────────┴──────────┴─────────────────────┴───────┘

### read the curves for the cluster + sector

In [18]:
curves = pl.read_excel("/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/ctm format curves.xlsx")

In [19]:
curves

shape: (1_320, 12)
┌────────────┬─────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ Netbeheerd ┆ Cluster ┆ Sector     ┆ Energiedra ┆ … ┆ 2040      ┆ 2045      ┆ 2050      ┆ Eenheid │
│ er         ┆ ---     ┆ ---        ┆ ger        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---     │
│ ---        ┆ str     ┆ str        ┆ ---        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str     │
│ str        ┆         ┆            ┆ str        ┆   ┆           ┆           ┆           ┆         │
╞════════════╪═════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ Stedin     ┆ Overig  ┆ Other      ┆ elektricit ┆ … ┆ 126.25    ┆ 176.75    ┆ 227.25    ┆ GWh     │
│            ┆         ┆            ┆ eit        ┆   ┆           ┆           ┆           ┆         │
│ Stedin     ┆ Overig  ┆ Aluminium  ┆ elektricit ┆ … ┆ 12.113737 ┆ 12.220915 ┆ 12.334948 ┆ GWh     │
│            ┆         ┆            ┆ eit        ┆   ┆           ┆           ┆           ┆         │
│ Stedin     ┆ Overig  ┆ Constructi ┆ elektricit ┆ … ┆ 258.23522 ┆ 282.03666 ┆ 306.74288 ┆ GWh     │
│            ┆         ┆ on         ┆ eit        ┆   ┆ 9         ┆           ┆ 6         ┆         │
│ Stedin     ┆ Overig  ┆ Food       ┆ elektricit ┆ … ┆ 1880.6536 ┆ 2352.9822 ┆ 2830.6877 ┆ GWh     │
│            ┆         ┆            ┆ eit        ┆   ┆ 85        ┆ 24        ┆ 63        ┆         │
│ Stedin     ┆ Overig  ┆ Machinery  ┆ elektricit ┆ … ┆ 278.34585 ┆ 327.32113 ┆ 378.89659 ┆ GWh     │
│            ┆         ┆            ┆ eit        ┆   ┆ 4         ┆ 9         ┆ 6         ┆         │
│ …          ┆ …       ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ Enexis     ┆ overig  ┆ Transport  ┆ gas        ┆ … ┆ 21.733    ┆ 21.733    ┆ 21.733    ┆ GWh     │
│            ┆         ┆ equipment  ┆            ┆   ┆           ┆           ┆           ┆         │
│ Enexis     ┆ overig  ┆ Transport  ┆ waterstof  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ GWh     │
│            ┆         ┆ equipment  ┆            ┆   ┆           ┆           ┆           ┆         │
│ Enexis     ┆ overig  ┆ Wood and   ┆ elektricit ┆ … ┆ 109.636   ┆ 109.636   ┆ 109.636   ┆ GWh     │
│            ┆         ┆ wood       ┆ eit        ┆   ┆           ┆           ┆           ┆         │
│            ┆         ┆ products   ┆            ┆   ┆           ┆           ┆           ┆         │
│ Enexis     ┆ overig  ┆ Wood and   ┆ gas        ┆ … ┆ 23.693    ┆ 23.693    ┆ 23.693    ┆ GWh     │
│            ┆         ┆ wood       ┆            ┆   ┆           ┆           ┆           ┆         │
│            ┆         ┆ products   ┆            ┆   ┆           ┆           ┆           ┆         │
│ Enexis     ┆ overig  ┆ Wood and   ┆ waterstof  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ GWh     │
│            ┆         ┆ wood       ┆            ┆   ┆           ┆           ┆           ┆         │
│            ┆         ┆ products   ┆            ┆   ┆           ┆           ┆           ┆         │
└────────────┴─────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [83]:
SCENARIO_YEARS = ['2030', '2035', '2040', '2050']
REFERENCE_YEAR = '2024'

ALL_YEARS = [REFERENCE_YEAR] + SCENARIO_YEARS

sums = curves.group_by(['Cluster', 'Sector', 'Scenario', 'Energiedrager']
                ).agg(
                    [pl.col(i).sum() for i in ALL_YEARS]
                ).sort(['Cluster', 'Sector', 'Scenario', 'Energiedrager'])


sums = sums.with_columns(replaced=pl.col("Cluster").replace('overig', 'Cluster 6').replace('Overig', 'Cluster 6'))
sums = sums.with_columns(pl.col('replaced').alias('Cluster')).drop('replaced')

In [84]:
sums

shape: (1_175, 9)
┌───────────┬──────────┬────────────┬───────────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ Cluster   ┆ Sector   ┆ Scenario   ┆ Energiedrager ┆ … ┆ 2030    ┆ 2035    ┆ 2040    ┆ 2050    │
│ ---       ┆ ---      ┆ ---        ┆ ---           ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str       ┆ str      ┆ str        ┆ str           ┆   ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞═══════════╪══════════╪════════════╪═══════════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ Chemelot  ┆ Food     ┆ Hoekpunt_E ┆ elektriciteit ┆ … ┆ 0.801   ┆ 0.816   ┆ 0.816   ┆ 0.816   │
│ Chemelot  ┆ Food     ┆ Hoekpunt_E ┆ gas           ┆ … ┆ 0.038   ┆ 0.0     ┆ 0.0     ┆ 0.0     │
│ Chemelot  ┆ Food     ┆ Hoekpunt_E ┆ waterstof     ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ 0.0     │
│ Chemelot  ┆ Food     ┆ Hoekpunt_G ┆ elektriciteit ┆ … ┆ 0.801   ┆ 0.816   ┆ 0.816   ┆ 0.816   │
│ Chemelot  ┆ Food     ┆ Hoekpunt_G ┆ gas           ┆ … ┆ 0.038   ┆ 0.0     ┆ 0.0     ┆ 0.0     │
│ …         ┆ …        ┆ …          ┆ …             ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ Cluster 6 ┆ Wood and ┆ Midden     ┆ gas           ┆ … ┆ 17.177  ┆ 11.846  ┆ 11.254  ┆ 5.923   │
│           ┆ wood     ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│           ┆ products ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│ Cluster 6 ┆ Wood and ┆ Midden     ┆ waterstof     ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.592   ┆ 5.923   │
│           ┆ wood     ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│           ┆ products ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│ Cluster 6 ┆ Wood and ┆ Vertraagd  ┆ elektriciteit ┆ … ┆ 108.599 ┆ 109.636 ┆ 109.636 ┆ 109.636 │
│           ┆ wood     ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│           ┆ products ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│ Cluster 6 ┆ Wood and ┆ Vertraagd  ┆ gas           ┆ … ┆ 27.839  ┆ 23.693  ┆ 23.693  ┆ 23.693  │
│           ┆ wood     ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│           ┆ products ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│ Cluster 6 ┆ Wood and ┆ Vertraagd  ┆ waterstof     ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ 0.0     │
│           ┆ wood     ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
│           ┆ products ┆            ┆               ┆   ┆         ┆         ┆         ┆         │
└───────────┴──────────┴────────────┴───────────────┴───┴─────────┴─────────┴─────────┴─────────┘

### the mapping

In [22]:
maps = pl.read_excel('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/CTM-DSH site mapping.xlsx')

Could not determine dtype for column 4, falling back to string

In [28]:
MARKER_VALUES = ['Bestaande niet-bottom-up sites', 'Bottom-up sites', 'New sites']  

df = maps.with_columns(
    pl.when(pl.col('Name').is_in(MARKER_VALUES))
      .then(pl.col('Name'))
      .otherwise(None)
      .forward_fill()
      .alias('category')
)

df = df.filter(~pl.col('Name').is_in(MARKER_VALUES))

In [29]:
df.write_csv('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/mapping.csv')

In [65]:
from pathlib import Path

def read_and_transform_mapping(
        excel_path: str,
        markers: list = ['Bestaande niet-bottom-up sites', 'Bottom-up sites', 'New sites'],
        marker_column_name:str = 'Name',
        save_file: bool = False,
        save_path: str = '' # if empty defaults to location of original file
) -> pl.DataFrame:
    
    maps = pl.read_excel(excel_path)
    df = maps.with_columns(
        pl.when(pl.col(marker_column_name).is_in(markers))
        .then(pl.col(marker_column_name))
        .otherwise(None)
        .forward_fill()
        .alias('category')
    )

    df = df.filter(~pl.col(marker_column_name).is_in(markers))

    result = df.with_columns([pl.when(pl.col('category')=='New sites')
                 .then(pl.lit(True))
                 .otherwise(False)
                 .alias('New site'),
                 
                 pl.when(pl.col('category')=='Bottom-up sites')
                 .then(pl.lit(True))
                 .otherwise(False)
                 .alias('Bottom-up')
                 ])

    if save_file:
        if save_path == '':
            save_path = Path(excel_path).parent
            
        result.write_csv(f'{save_path}/mapping.csv')

    return result

In [66]:
res = read_and_transform_mapping(excel_path='/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/CTM-DSH site mapping.xlsx')

Could not determine dtype for column 4, falling back to string

In [69]:
res

shape: (531, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ Name      ┆ Name refo ┆ Sector    ┆ Cluster   ┆ … ┆ DSH plant ┆ category  ┆ New site ┆ Bottom-up │
│ ---       ┆ rmatted   ┆ ---       ┆ ---       ┆   ┆ id        ┆ ---       ┆ ---      ┆ ---       │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ bool     ┆ bool      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ A12 CPP   ┆ a12_cpp_p ┆ Other     ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Petrogas  ┆ etrogas_e ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ EP Nether ┆ p_netherl ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│ land…     ┆ and…      ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Aardgasbu ┆ aardgasbu ┆ Other     ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ ffer Zuid ┆ ffer_zuid ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ wending   ┆ wending   ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Abbott    ┆ abbott_he ┆ Other     ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Healthcar ┆ althcare_ ┆ chemicals ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ e         ┆ products  ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│ Products  ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Abbott    ┆ abbott_la ┆ Food      ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Laborator ┆ boratorie ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ ies       ┆ s         ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ ADM       ┆ adm_europ ┆ Food      ┆ Rotterdam ┆ … ┆ 527be9a2- ┆ Bestaande ┆ false    ┆ false     │
│ Europoort ┆ oort      ┆           ┆ -Moerdijk ┆   ┆ 5258-4cda ┆ niet-bott ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆ -89cb-b48 ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆ 520…      ┆ sites     ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site230## ┆ site230## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site231## ┆ site231## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site232## ┆ site232## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site233## ┆ site233## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site234## ┆ site234## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [ ]:
# res2 = res.with_columns([pl.when(pl.col('category')=='New sites')
#                  .then(pl.lit(True))
#                  .otherwise(False)
#                  .alias('New site'),
                 
#                  pl.when(pl.col('category')=='Bottom-up sites')
#                  .then(pl.lit(True))
#                  .otherwise(False)
#                  .alias('Bottom-up')
#                  ])

In [44]:
res2

shape: (531, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ Name      ┆ Name refo ┆ Sector    ┆ Cluster   ┆ … ┆ DSH plant ┆ category  ┆ New site ┆ Bottom-up │
│ ---       ┆ rmatted   ┆ ---       ┆ ---       ┆   ┆ id        ┆ ---       ┆ ---      ┆ ---       │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ bool     ┆ bool      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ A12 CPP   ┆ a12_cpp_p ┆ Other     ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Petrogas  ┆ etrogas_e ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ EP Nether ┆ p_netherl ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│ land…     ┆ and…      ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Aardgasbu ┆ aardgasbu ┆ Other     ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ ffer Zuid ┆ ffer_zuid ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ wending   ┆ wending   ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Abbott    ┆ abbott_he ┆ Other     ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Healthcar ┆ althcare_ ┆ chemicals ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ e         ┆ products  ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│ Products  ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Abbott    ┆ abbott_la ┆ Food      ┆ Cluster 6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Laborator ┆ boratorie ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ ies       ┆ s         ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ ADM       ┆ adm_europ ┆ Food      ┆ Rotterdam ┆ … ┆ 527be9a2- ┆ Bestaande ┆ false    ┆ false     │
│ Europoort ┆ oort      ┆           ┆ -Moerdijk ┆   ┆ 5258-4cda ┆ niet-bott ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆ -89cb-b48 ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆ 520…      ┆ sites     ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site230## ┆ site230## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site231## ┆ site231## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site232## ┆ site232## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site233## ┆ site233## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ Gebruiker ┆ Gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site234## ┆ site234## ┆ stuurt op ┆ stuurt op ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ via API   ┆ via API   ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘