In [6]:
import polars as pl
from read_DSH_files import *
from constants import EMISSION_COLS_ORDER, UTILITY_COLS_ORDER

In [7]:
plant_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/Sprint 2 CTM upload/ADM Europoort.xlsx'

In [10]:
pr = read_production_table(plant_path)

In [14]:
pr.schema

Schema([('Scenario', String),
        ('Year', String),
        ('Capacity', String),
        ('FLH', String),
        ('Efficiency electricity', String),
        ('Efficiency heat', String)])

In [13]:
another_test_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/Sprint 2 CTM upload/Air Liquide Bergen op Zoom.xlsx'
x = read_production_table(another_test_path)
x

shape: (0, 0)
┌┐
╞╡
└┘

In [12]:
type(x)
len(x)

0

In [25]:
scens = read_all_scenario_sheets(
    workbook_path=plant_path,
    emission_cols=EMISSION_COLS_ORDER,
    energy_cols=UTILITY_COLS_ORDER, 
    reference_year=2024,
    aggregate_flow_types=True
).sort(['Scenario', 'Year', 'Flow type'])
scens

shape: (40, 27)
┌────────────────┬──────┬────────────┬─────────┬───┬─────────┬──────────┬──────────────────┬───────┐
│ Scenario       ┆ Year ┆ Flow type  ┆ CO2     ┆ … ┆ Ammonia ┆ Methanol ┆ Other syn fuel   ┆ Other │
│ ---            ┆ ---  ┆ ---        ┆ ---     ┆   ┆ ---     ┆ ---      ┆ and raw materia… ┆ ---   │
│ str            ┆ str  ┆ str        ┆ f64     ┆   ┆ i64     ┆ i64      ┆ ---              ┆ i64   │
│                ┆      ┆            ┆         ┆   ┆         ┆          ┆ i64              ┆       │
╞════════════════╪══════╪════════════╪═════════╪═══╪═════════╪══════════╪══════════════════╪═══════╡
│ Elektrificatie ┆ 2030 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Elektrificatie ┆ 2030 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Elektrificatie ┆ 2035 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Elektrificatie ┆ 2035 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Elektrificatie ┆ 2040 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ …              ┆ …    ┆ …          ┆ …       ┆ … ┆ …       ┆ …        ┆ …                ┆ …     │
│ Waterstof      ┆ 2035 ┆ production ┆ 130.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Waterstof      ┆ 2040 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Waterstof      ┆ 2040 ┆ production ┆ 130.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Waterstof      ┆ 2050 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Waterstof      ┆ 2050 ┆ production ┆ -4.703  ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
└────────────────┴──────┴────────────┴─────────┴───┴─────────┴──────────┴──────────────────┴───────┘

In [ ]:
scens_midden = scens.filter(pl.col('Scenario') == 'Midden')
scens_midden

shape: (8, 27)
┌──────────┬──────┬────────────┬─────────┬───┬─────────┬──────────┬────────────────────────┬───────┐
│ Scenario ┆ Year ┆ Flow type  ┆ CO2     ┆ … ┆ Ammonia ┆ Methanol ┆ Other syn fuel and raw ┆ Other │
│ ---      ┆ ---  ┆ ---        ┆ ---     ┆   ┆ ---     ┆ ---      ┆ materia…               ┆ ---   │
│ str      ┆ str  ┆ str        ┆ f64     ┆   ┆ i64     ┆ i64      ┆ ---                    ┆ i64   │
│          ┆      ┆            ┆         ┆   ┆         ┆          ┆ i64                    ┆       │
╞══════════╪══════╪════════════╪═════════╪═══╪═════════╪══════════╪════════════════════════╪═══════╡
│ Midden   ┆ 2030 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
│ Midden   ┆ 2030 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
│ Midden   ┆ 2035 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
│ Midden   ┆ 2035 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
│ Midden   ┆ 2040 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
│ Midden   ┆ 2040 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
│ Midden   ┆ 2050 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
│ Midden   ┆ 2050 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                      ┆ 0     │
└──────────┴──────┴────────────┴─────────┴───┴─────────┴──────────┴────────────────────────┴───────┘

### TEst modular functions

In [1]:
from push_to_ctm_modules import *
from constants import EMISSION_COLS_ORDER, UTILITY_COLS_ORDER

In [2]:
xlsx_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/test_input'
mapping_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/CTM-DSH site mapping.xlsx'

In [3]:
all_scenario_data, scenario_year_groups, logs, errors = load_all_plants_scenario_data(
    plants_workbook_dir=xlsx_path,
    mapping_file=mapping_path,
    emission_cols=EMISSION_COLS_ORDER,
    energy_cols=UTILITY_COLS_ORDER,
)

Could not determine dtype for column 4, falling back to string

In [4]:
all_scenario_data['527be9a2-5258-4cda-89cb-b485207a42d0']['df_production']

shape: (20, 6)
┌───────────┬──────┬──────────┬────────────────┬────────────────────────┬─────────────────┐
│ Scenario  ┆ Year ┆ Capacity ┆ FLH            ┆ Efficiency electricity ┆ Efficiency heat │
│ ---       ┆ ---  ┆ ---      ┆ ---            ┆ ---                    ┆ ---             │
│ str       ┆ str  ┆ str      ┆ str            ┆ str                    ┆ str             │
╞═══════════╪══════╪══════════╪════════════════╪════════════════════════╪═════════════════╡
│ Midden    ┆ 2030 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ Midden    ┆ 2035 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ Midden    ┆ 2040 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ Midden    ┆ 2050 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ VT        ┆ 2030 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ …         ┆ …    ┆ …        ┆ …              ┆ …                      ┆ …               │
│ Waterstof ┆ 2050 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ Groen gas ┆ 2030 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ Groen gas ┆ 2035 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ Groen gas ┆ 2040 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
│ Groen gas ┆ 2050 ┆ 22.5     ┆ 7125.733333333 ┆ 33                     ┆ 61              │
└───────────┴──────┴──────────┴────────────────┴────────────────────────┴─────────────────┘

In [6]:
test_scenario = all_scenario_data['527be9a2-5258-4cda-89cb-b485207a42d0']['df']
test_scenario

shape: (40, 27)
┌────────────────┬──────┬────────────┬─────────┬───┬─────────┬──────────┬──────────────────┬───────┐
│ Scenario       ┆ Year ┆ Flow type  ┆ CO2     ┆ … ┆ Ammonia ┆ Methanol ┆ Other syn fuel   ┆ Other │
│ ---            ┆ ---  ┆ ---        ┆ ---     ┆   ┆ ---     ┆ ---      ┆ and raw materia… ┆ ---   │
│ str            ┆ str  ┆ str        ┆ f64     ┆   ┆ i64     ┆ i64      ┆ ---              ┆ i64   │
│                ┆      ┆            ┆         ┆   ┆         ┆          ┆ i64              ┆       │
╞════════════════╪══════╪════════════╪═════════╪═══╪═════════╪══════════╪══════════════════╪═══════╡
│ Midden         ┆ 2030 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Midden         ┆ 2035 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Midden         ┆ 2040 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Midden         ┆ 2050 ┆ production ┆ 126.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ VT             ┆ 2030 ┆ production ┆ 135.297 ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ …              ┆ …    ┆ …          ┆ …       ┆ … ┆ …       ┆ …        ┆ …                ┆ …     │
│ Midden         ┆ 2040 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ VT             ┆ 2030 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Waterstof      ┆ 2050 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ Elektrificatie ┆ 2035 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
│ VT             ┆ 2040 ┆ demand     ┆ 0.0     ┆ … ┆ 0       ┆ 0        ┆ 0                ┆ 0     │
└────────────────┴──────┴────────────┴─────────┴───┴─────────┴──────────┴──────────────────┴───────┘

In [7]:
next(iter(scenario_year_groups))

('Midden', '2030', 'production')

In [8]:
scenario_year_groups[('Midden', '2030', 'production')][2]

('f508a9b5-c7ad-4b51-8a32-78661789e81f',
 {'Scenario': 'Midden',
  'Year': '2030',
  'Flow type': 'production',
  'CO2': 2242,
  'Methane': 0,
  'N2O': 12,
  'F-gases': 0,
  'CO2 (fossil) CCU/CCS': 0,
  'CO2 (bio) CCU/CCS': 0,
  'Electricity': 0,
  'Electricity_peak': 0,
  'Natural Gas': 0,
  'Hydrogen ( >98% vol.%) (LHV)': 0,
  'Hydrogen ( <98% vol.%) (LHV)': 0,
  'Heat': 0,
  'Residual gases': 5000,
  'Coal and coal products': 0,
  'Oil and oil products': 0.0,
  'Biomass (liquid)': 0,
  'Biomass (solid)': 0,
  'Green gas': 0,
  'Waste (fossil)': 0,
  'Waste (bio)': 0,
  'Ammonia': 0,
  'Methanol': 0,
  'Other syn fuel and raw materials': 0,
  'Other': None})

In [5]:
inputs, logs = build_ctm_inputs_from_plants(
    plants_in_group=scenario_year_groups[('Midden', '2030', 'demand')],  # from scenario_year_groups
    all_scenario_data=all_scenario_data,
    emission_cols=EMISSION_COLS_ORDER,
    energy_cols=UTILITY_COLS_ORDER,
    flow_type="demand",
)

In [15]:
inputs

NameError: name 'inputs' is not defined

In [8]:
from utils import *


sector_curves = get_aggregated_curves('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/ctm format curves.xlsx')

In [11]:
sector_curves

shape: (1_175, 10)
┌──────────┬──────────┬────────────┬────────────────┬───┬─────────┬─────────┬─────────┬────────────┐
│ Cluster  ┆ Sector   ┆ Scenario   ┆ Energiedrager  ┆ … ┆ 2035    ┆ 2040    ┆ 2050    ┆ replaced   │
│ ---      ┆ ---      ┆ ---        ┆ ---            ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---        │
│ str      ┆ str      ┆ str        ┆ str            ┆   ┆ f64     ┆ f64     ┆ f64     ┆ str        │
╞══════════╪══════════╪════════════╪════════════════╪═══╪═════════╪═════════╪═════════╪════════════╡
│ Chemelot ┆ Food     ┆ Hoekpunt_E ┆ elektriciteit  ┆ … ┆ 0.816   ┆ 0.816   ┆ 0.816   ┆ Hoekpunt_E │
│ Chemelot ┆ Food     ┆ Hoekpunt_E ┆ gas            ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ Hoekpunt_E │
│ Chemelot ┆ Food     ┆ Hoekpunt_E ┆ waterstof      ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ Hoekpunt_E │
│ Chemelot ┆ Food     ┆ Hoekpunt_G ┆ elektriciteit  ┆ … ┆ 0.816   ┆ 0.816   ┆ 0.816   ┆ Hoekpunt_G │
│ Chemelot ┆ Food     ┆ Hoekpunt_G ┆ gas            ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ Hoekpunt_G │
│ …        ┆ …        ┆ …          ┆ …              ┆ … ┆ …       ┆ …       ┆ …       ┆ …          │
│ overig   ┆ Wood and ┆ Midden     ┆ gas            ┆ … ┆ 11.846  ┆ 11.254  ┆ 5.923   ┆ Midden     │
│          ┆ wood     ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│          ┆ products ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│ overig   ┆ Wood and ┆ Midden     ┆ waterstof      ┆ … ┆ 0.0     ┆ 0.592   ┆ 5.923   ┆ Midden     │
│          ┆ wood     ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│          ┆ products ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│ overig   ┆ Wood and ┆ Vertraagd  ┆ elektriciteit  ┆ … ┆ 109.636 ┆ 109.636 ┆ 109.636 ┆ Vertraagd  │
│          ┆ wood     ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│          ┆ products ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│ overig   ┆ Wood and ┆ Vertraagd  ┆ gas            ┆ … ┆ 23.693  ┆ 23.693  ┆ 23.693  ┆ Vertraagd  │
│          ┆ wood     ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│          ┆ products ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│ overig   ┆ Wood and ┆ Vertraagd  ┆ waterstof      ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ Vertraagd  │
│          ┆ wood     ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
│          ┆ products ┆            ┆                ┆   ┆         ┆         ┆         ┆            │
└──────────┴──────────┴────────────┴────────────────┴───┴─────────┴─────────┴─────────┴────────────┘

In [10]:
build_ctm_inputs_from_cluster_sector(sector_curves, None, None)

({}, [])

In [17]:
from utils import *
from push_to_ctm_modules import build_ctm_inputs_from_cluster_sector

In [4]:
curve_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/ctm format curves.xlsx'
reshaped = get_final_cluster_sector_curves(curve_path, SCENARIO_YEARS)
wow = build_ctm_inputs_from_cluster_sector(reshaped)

In [5]:
wow

({'food&&chemelot&&cluster&&electricity_demand': '0.765',
  'food&&chemelot&&cluster&&natural_gas_demand': '0.122',
  'food&&chemelot&&cluster&&hydrogen_(>98%_vol%)_demand': '0.006',
  'machinery&&chemelot&&cluster&&electricity_demand': '0.225',
  'machinery&&chemelot&&cluster&&natural_gas_demand': '0.099',
  'machinery&&chemelot&&cluster&&hydrogen_(>98%_vol%)_demand': '0.001',
  'other_chemicals&&chemelot&&cluster&&electricity_demand': '21.446',
  'other_chemicals&&chemelot&&cluster&&natural_gas_demand': '17.693',
  'other_chemicals&&chemelot&&cluster&&hydrogen_(>98%_vol%)_demand': '8.847',
  'paper&&chemelot&&cluster&&electricity_demand': '0.018',
  'paper&&chemelot&&cluster&&natural_gas_demand': '0.009',
  'paper&&chemelot&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'wood_and_wood_products&&chemelot&&cluster&&electricity_demand': '1.287',
  'wood_and_wood_products&&chemelot&&cluster&&natural_gas_demand': '0.165',
  'wood_and_wood_products&&chemelot&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'aluminium&&cluster_6&&cluster&&electricity_demand': '53.219963',
  'aluminium&&cluster_6&&cluster&&natural_gas_demand': '34.009655432730305',
  'aluminium&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '0.38',
  'construction&&cluster_6&&cluster&&electricity_demand': '459.4962832339998',
  'construction&&cluster_6&&cluster&&natural_gas_demand': '14.300193663134111',
  'construction&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '111.77777786720003',
  'food&&cluster_6&&cluster&&electricity_demand': '6675.17163499938',
  'food&&cluster_6&&cluster&&natural_gas_demand': '1102.1303983312732',
  'food&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '2723.674268711372',
  'machinery&&cluster_6&&cluster&&electricity_demand': '2458.6142719552004',
  'machinery&&cluster_6&&cluster&&natural_gas_demand': '616.4601497455524',
  'machinery&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '525.3020004164002',
  'mining_and_quarrying&&cluster_6&&cluster&&electricity_demand': '175.27760739562424',
  'mining_and_quarrying&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '-5.925833338074034',
  'non_metallic_minerals&&cluster_6&&cluster&&electricity_demand': '1928.241583348066',
  'non_metallic_minerals&&cluster_6&&cluster&&natural_gas_demand': '783.8602253665803',
  'non_metallic_minerals&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '212.39151478983302',
  'other&&cluster_6&&cluster&&electricity_demand': '1709.4880042209998',
  'other&&cluster_6&&cluster&&natural_gas_demand': '224.9289259083469',
  'other&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '718.5513338652116',
  'other_chemicals&&cluster_6&&cluster&&electricity_demand': '1243.330422',
  'other_chemicals&&cluster_6&&cluster&&natural_gas_demand': '407.2657044102157',
  'other_chemicals&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '201.9394812766734',
  'other_metals&&cluster_6&&cluster&&electricity_demand': '119.67915250384',
  'other_metals&&cluster_6&&cluster&&natural_gas_demand': '45.0402089987438',
  'other_metals&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '23.376265054531103',
  'paper&&cluster_6&&cluster&&electricity_demand': '649.7495269462',
  'paper&&cluster_6&&cluster&&natural_gas_demand': '81.19126488698214',
  'paper&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '52.216816000675564',
  'refineries&&cluster_6&&cluster&&electricity_demand': '30.285066',
  'refineries&&cluster_6&&cluster&&natural_gas_demand': '2.0636211255036',
  'refineries&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'steel&&cluster_6&&cluster&&electricity_demand': '97.11544799999999',
  'steel&&cluster_6&&cluster&&natural_gas_demand': '39.1422949044477',
  'steel&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '0.368',
  'textile_and_leather&&cluster_6&&cluster&&electricity_demand': '202.37055031337997',
  'textile_and_leather&&cluster_6&&cluster&&natural_gas_demand': '67.58815904228081',
  'textile_and_leather&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '-33.25555558216006',
  'transport_equipment&&cluster_6&&cluster&&electricity_demand': '298.43038685101993',
  'transport_equipment&&cluster_6&&cluster&&natural_gas_demand': '26.691697919265998',
  'transport_equipment&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '18.950000015159947',
  'wood_and_wood_products&&cluster_6&&cluster&&electricity_demand': '114.40619043750401',
  'wood_and_wood_products&&cluster_6&&cluster&&natural_gas_demand': '24.0144953594423',
  'wood_and_wood_products&&cluster_6&&cluster&&hydrogen_(>98%_vol%)_demand': '-5.422222226559995',
  'aluminium&&noord_nederland&&cluster&&electricity_demand': '21.525',
  'aluminium&&noord_nederland&&cluster&&natural_gas_demand': '17.255',
  'aluminium&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.194',
  'food&&noord_nederland&&cluster&&electricity_demand': '100.85',
  'food&&noord_nederland&&cluster&&natural_gas_demand': '2.922',
  'food&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.154',
  'machinery&&noord_nederland&&cluster&&electricity_demand': '33.364',
  'machinery&&noord_nederland&&cluster&&natural_gas_demand': '11.765',
  'machinery&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.095',
  'non_metallic_minerals&&noord_nederland&&cluster&&electricity_demand': '0.335',
  'non_metallic_minerals&&noord_nederland&&cluster&&natural_gas_demand': '0.049',
  'non_metallic_minerals&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.008',
  'other&&noord_nederland&&cluster&&electricity_demand': '0.608',
  'other&&noord_nederland&&cluster&&natural_gas_demand': '0.016',
  'other&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'other_chemicals&&noord_nederland&&cluster&&electricity_demand': '49.453',
  'other_chemicals&&noord_nederland&&cluster&&natural_gas_demand': '0.375',
  'other_chemicals&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.188',
  'refineries&&noord_nederland&&cluster&&electricity_demand': '7.189',
  'steel&&noord_nederland&&cluster&&electricity_demand': '0.87',
  'textile_and_leather&&noord_nederland&&cluster&&electricity_demand': '0.149',
  'textile_and_leather&&noord_nederland&&cluster&&natural_gas_demand': '0.017',
  'textile_and_leather&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'transport_equipment&&noord_nederland&&cluster&&electricity_demand': '0.391',
  'transport_equipment&&noord_nederland&&cluster&&natural_gas_demand': '0.234',
  'transport_equipment&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'wood_and_wood_products&&noord_nederland&&cluster&&electricity_demand': '0.138',
  'wood_and_wood_products&&noord_nederland&&cluster&&natural_gas_demand': '0.131',
  'wood_and_wood_products&&noord_nederland&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'construction&&rotterdam_moerdijk&&cluster&&electricity_demand': '18.228638500000006',
  'construction&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '0.4178440052253',
  'construction&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'food&&rotterdam_moerdijk&&cluster&&electricity_demand': '146.27053899999993',
  'food&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '4.20309462634732',
  'food&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '0.22079445401828002',
  'machinery&&rotterdam_moerdijk&&cluster&&electricity_demand': '109.018617',
  'machinery&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '19.76483732846685',
  'machinery&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '0.131',
  'mining_and_quarrying&&rotterdam_moerdijk&&cluster&&electricity_demand': '30.251497',
  'non_metallic_minerals&&rotterdam_moerdijk&&cluster&&electricity_demand': '144.387163',
  'non_metallic_minerals&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '42.997932056452164',
  'non_metallic_minerals&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '7.258895916166632',
  'other&&rotterdam_moerdijk&&cluster&&electricity_demand': '31.781257000000004',
  'other&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '3.9973119669865',
  'other&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '1.61',
  'other_chemicals&&rotterdam_moerdijk&&cluster&&electricity_demand': '262.577773',
  'other_chemicals&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '12.877778045830565',
  'other_chemicals&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '6.428696649438935',
  'other_metals&&rotterdam_moerdijk&&cluster&&electricity_demand': '15.401513000000001',
  'paper&&rotterdam_moerdijk&&cluster&&electricity_demand': '5.017421999999999',
  'paper&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '1.1977799671632718',
  'paper&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '0.076262551095528',
  'refineries&&rotterdam_moerdijk&&cluster&&electricity_demand': '125.49507600000001',
  'steel&&rotterdam_moerdijk&&cluster&&electricity_demand': '3.061443',
  'steel&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '0.0',
  'steel&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'transport_equipment&&rotterdam_moerdijk&&cluster&&electricity_demand': '17.758155000000002',
  'transport_equipment&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '0.9425031179652003',
  'transport_equipment&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'wood_and_wood_products&&rotterdam_moerdijk&&cluster&&electricity_demand': '6.808681',
  'wood_and_wood_products&&rotterdam_moerdijk&&cluster&&natural_gas_demand': '0.056260478832150004',
  'wood_and_wood_products&&rotterdam_moerdijk&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'aluminium&&zeeland_west_brabant&&cluster&&electricity_demand': '83.60520899999999',
  'aluminium&&zeeland_west_brabant&&cluster&&natural_gas_demand': '163.5273394707501',
  'aluminium&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'construction&&zeeland_west_brabant&&cluster&&electricity_demand': '17.2324095',
  'construction&&zeeland_west_brabant&&cluster&&natural_gas_demand': '0.43345813013730006',
  'construction&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'food&&zeeland_west_brabant&&cluster&&electricity_demand': '748.077192',
  'food&&zeeland_west_brabant&&cluster&&natural_gas_demand': '160.0607458919569',
  'food&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '8.42419715220826',
  'machinery&&zeeland_west_brabant&&cluster&&electricity_demand': '41.596756000000006',
  'machinery&&zeeland_west_brabant&&cluster&&natural_gas_demand': '6.931759396732599',
  'machinery&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.018',
  'mining_and_quarrying&&zeeland_west_brabant&&cluster&&electricity_demand': '3.080369',
  'non_metallic_minerals&&zeeland_west_brabant&&cluster&&electricity_demand': '8.942289999999998',
  'non_metallic_minerals&&zeeland_west_brabant&&cluster&&natural_gas_demand': '0.930670224078342',
  'non_metallic_minerals&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.15408585043135803',
  'other&&zeeland_west_brabant&&cluster&&electricity_demand': '183.1344135',
  'other&&zeeland_west_brabant&&cluster&&natural_gas_demand': '3.9242453804797495',
  'other&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.139',
  'other_chemicals&&zeeland_west_brabant&&cluster&&electricity_demand': '92.75538900000002',
  'other_chemicals&&zeeland_west_brabant&&cluster&&natural_gas_demand': '57.363436553948745',
  'other_chemicals&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '28.252931437019534',
  'paper&&zeeland_west_brabant&&cluster&&electricity_demand': '82.53007600000002',
  'paper&&zeeland_west_brabant&&cluster&&natural_gas_demand': '2.4508239337746076',
  'paper&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.15479727236859198',
  'refineries&&zeeland_west_brabant&&cluster&&electricity_demand': '12.584942999999999',
  'refineries&&zeeland_west_brabant&&cluster&&natural_gas_demand': '31.113995047469096',
  'refineries&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'steel&&zeeland_west_brabant&&cluster&&electricity_demand': '0.172804',
  'textile_and_leather&&zeeland_west_brabant&&cluster&&electricity_demand': '0.170421',
  'transport_equipment&&zeeland_west_brabant&&cluster&&electricity_demand': '28.769334499999996',
  'transport_equipment&&zeeland_west_brabant&&cluster&&natural_gas_demand': '2.3980812989973',
  'transport_equipment&&zeeland_west_brabant&&cluster&&hydrogen_(>98%_vol%)_demand': '0.0',
  'wood_and_wood_products&&zeeland_west_brabant&&cluster&&electricity_demand': '3.285118'},
 ['Cluster-sector: food/chemelot/electricity/demand = 0.801',
  'Cluster-sector: food/chemelot/natural_gas/demand = 0.038',
  'Cluster-sector: food/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: food/chemelot/electricity/demand = 0.801',
  'Cluster-sector: food/chemelot/natural_gas/demand = 0.038',
  'Cluster-sector: food/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: food/chemelot/electricity/demand = 0.756',
  'Cluster-sector: food/chemelot/natural_gas/demand = 0.151',
  'Cluster-sector: food/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: food/chemelot/electricity/demand = 0.779',
  'Cluster-sector: food/chemelot/natural_gas/demand = 0.093',
  'Cluster-sector: food/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: food/chemelot/electricity/demand = 0.756',
  'Cluster-sector: food/chemelot/natural_gas/demand = 0.151',
  'Cluster-sector: food/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: machinery/chemelot/electricity/demand = 0.224',
  'Cluster-sector: machinery/chemelot/natural_gas/demand = 0.09',
  'Cluster-sector: machinery/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: machinery/chemelot/electricity/demand = 0.224',
  'Cluster-sector: machinery/chemelot/natural_gas/demand = 0.09',
  'Cluster-sector: machinery/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: machinery/chemelot/electricity/demand = 0.216',
  'Cluster-sector: machinery/chemelot/natural_gas/demand = 0.111',
  'Cluster-sector: machinery/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: machinery/chemelot/electricity/demand = 0.219',
  'Cluster-sector: machinery/chemelot/natural_gas/demand = 0.101',
  'Cluster-sector: machinery/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: machinery/chemelot/electricity/demand = 0.216',
  'Cluster-sector: machinery/chemelot/natural_gas/demand = 0.111',
  'Cluster-sector: machinery/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: other_chemicals/chemelot/electricity/demand = 20.266',
  'Cluster-sector: other_chemicals/chemelot/natural_gas/demand = 27.719',
  'Cluster-sector: other_chemicals/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: other_chemicals/chemelot/electricity/demand = 20.266',
  'Cluster-sector: other_chemicals/chemelot/natural_gas/demand = 27.719',
  'Cluster-sector: other_chemicals/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: other_chemicals/chemelot/electricity/demand = 18.792',
  'Cluster-sector: other_chemicals/chemelot/natural_gas/demand = 29.194',
  'Cluster-sector: other_chemicals/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: other_chemicals/chemelot/electricity/demand = 19.087',
  'Cluster-sector: other_chemicals/chemelot/natural_gas/demand = 28.899',
  'Cluster-sector: other_chemicals/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: other_chemicals/chemelot/electricity/demand = 18.792',
  'Cluster-sector: other_chemicals/chemelot/natural_gas/demand = 29.194',
  'Cluster-sector: other_chemicals/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: paper/chemelot/electricity/demand = 0.02',
  'Cluster-sector: paper/chemelot/natural_gas/demand = 0.003',
  'Cluster-sector: paper/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: paper/chemelot/electricity/demand = 0.02',
  'Cluster-sector: paper/chemelot/natural_gas/demand = 0.003',
  'Cluster-sector: paper/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: paper/chemelot/electricity/demand = 0.018',
  'Cluster-sector: paper/chemelot/natural_gas/demand = 0.011',
  'Cluster-sector: paper/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: paper/chemelot/electricity/demand = 0.019',
  'Cluster-sector: paper/chemelot/natural_gas/demand = 0.007',
  'Cluster-sector: paper/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: paper/chemelot/electricity/demand = 0.018',
  'Cluster-sector: paper/chemelot/natural_gas/demand = 0.011',
  'Cluster-sector: paper/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: wood_and_wood_products/chemelot/electricity/demand = 1.316',
  'Cluster-sector: wood_and_wood_products/chemelot/natural_gas/demand = 0.049',
  'Cluster-sector: wood_and_wood_products/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: wood_and_wood_products/chemelot/electricity/demand = 1.316',
  'Cluster-sector: wood_and_wood_products/chemelot/natural_gas/demand = 0.049',
  'Cluster-sector: wood_and_wood_products/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: wood_and_wood_products/chemelot/electricity/demand = 1.28',
  'Cluster-sector: wood_and_wood_products/chemelot/natural_gas/demand = 0.194',
  'Cluster-sector: wood_and_wood_products/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: wood_and_wood_products/chemelot/electricity/demand = 1.298',
  'Cluster-sector: wood_and_wood_products/chemelot/natural_gas/demand = 0.12',
  'Cluster-sector: wood_and_wood_products/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: wood_and_wood_products/chemelot/electricity/demand = 1.28',
  'Cluster-sector: wood_and_wood_products/chemelot/natural_gas/demand = 0.194',
  'Cluster-sector: wood_and_wood_products/chemelot/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: aluminium/cluster_6/electricity/demand = 51.636511',
  'Cluster-sector: aluminium/cluster_6/natural_gas/demand = 35.91779567418498',
  'Cluster-sector: aluminium/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: aluminium/cluster_6/electricity/demand = 51.636511',
  'Cluster-sector: aluminium/cluster_6/natural_gas/demand = 35.91779567418498',
  'Cluster-sector: aluminium/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: aluminium/cluster_6/electricity/demand = 49.7254',
  'Cluster-sector: aluminium/cluster_6/natural_gas/demand = 37.829135000148796',
  'Cluster-sector: aluminium/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: aluminium/cluster_6/electricity/demand = 50.10759899999999',
  'Cluster-sector: aluminium/cluster_6/natural_gas/demand = 37.44593591563966',
  'Cluster-sector: aluminium/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: aluminium/cluster_6/electricity/demand = 49.7254',
  'Cluster-sector: aluminium/cluster_6/natural_gas/demand = 37.829135000148796',
  'Cluster-sector: aluminium/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: construction/cluster_6/electricity/demand = 323.84708864999976',
  'Cluster-sector: construction/cluster_6/natural_gas/demand = 69.78494507609439',
  'Cluster-sector: construction/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: construction/cluster_6/electricity/demand = 323.84708864999976',
  'Cluster-sector: construction/cluster_6/natural_gas/demand = 69.78494507609439',
  'Cluster-sector: construction/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: construction/cluster_6/electricity/demand = 221.78533389999976',
  'Cluster-sector: construction/cluster_6/natural_gas/demand = 63.39752523989448',
  'Cluster-sector: construction/cluster_6/hydrogen_(>98%_vol%)/demand = 0.0',
  'Cluster-sector: construction/cluster_6/electricity/demand = 104.16666675',

In [1]:
from utils import validate_mappings_against_ctm, fix_mapping_sector_cluster

# print("Validating mappings against CTM API...")
result = validate_mappings_against_ctm(
    mapping_file="data/ctm/input/CTM-DSH site mapping.xlsx",
    use_beta=True,
    output_report="validation_report.txt",
)

MIAAAAAAAAAAAAAAAAAAU

In [1]:
import polars as pl

In [13]:
curves_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/ctm format curves_3.xlsx'

In [14]:
curves = pl.read_excel(curves_path, sheet_id=0, raise_if_empty=False)

In [15]:
curves['wkk rest']

shape: (100, 8)
┌────────────────┬─────────┬────────┬──────┬────────────┬──────┬─────────────┬─────────────────┐
│ Scenario       ┆ Cluster ┆ Sector ┆ Year ┆ Capacity   ┆ FLH  ┆ Efficiency  ┆ Efficiency heat │
│ ---            ┆ ---     ┆ ---    ┆ ---  ┆ ---        ┆ ---  ┆ electricity ┆ ---             │
│ str            ┆ str     ┆ str    ┆ i64  ┆ f64        ┆ i64  ┆ ---         ┆ f64             │
│                ┆         ┆        ┆      ┆            ┆      ┆ f64         ┆                 │
╞════════════════╪═════════╪════════╪══════╪════════════╪══════╪═════════════╪═════════════════╡
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2024 ┆ 271.473897 ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2030 ┆ 190.031728 ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2035 ┆ 81.442169  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2040 ┆ 13.573695  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2050 ┆ 0.0        ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ …              ┆ …       ┆ …      ┆ …    ┆ …          ┆ …    ┆ …           ┆ …               │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2024 ┆ 100.258941 ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2030 ┆ 70.181259  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2035 ┆ 30.077682  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2040 ┆ 5.012947   ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2050 ┆ 0.0        ┆ 5580 ┆ 0.38        ┆ 0.5             │
└────────────────┴─────────┴────────┴──────┴────────────┴──────┴─────────────┴─────────────────┘

In [28]:
curves_production = curves['wkk rest']

In [17]:
curves_production

shape: (100, 8)
┌────────────────┬─────────┬────────┬──────┬────────────┬──────┬─────────────┬─────────────────┐
│ Scenario       ┆ Cluster ┆ Sector ┆ Year ┆ Capacity   ┆ FLH  ┆ Efficiency  ┆ Efficiency heat │
│ ---            ┆ ---     ┆ ---    ┆ ---  ┆ ---        ┆ ---  ┆ electricity ┆ ---             │
│ str            ┆ str     ┆ str    ┆ i64  ┆ f64        ┆ i64  ┆ ---         ┆ f64             │
│                ┆         ┆        ┆      ┆            ┆      ┆ f64         ┆                 │
╞════════════════╪═════════╪════════╪══════╪════════════╪══════╪═════════════╪═════════════════╡
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2024 ┆ 271.473897 ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2030 ┆ 190.031728 ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2035 ┆ 81.442169  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2040 ┆ 13.573695  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Elektrificatie ┆ Overig  ┆ Food   ┆ 2050 ┆ 0.0        ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ …              ┆ …       ┆ …      ┆ …    ┆ …          ┆ …    ┆ …           ┆ …               │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2024 ┆ 100.258941 ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2030 ┆ 70.181259  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2035 ┆ 30.077682  ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2040 ┆ 5.012947   ┆ 5580 ┆ 0.38        ┆ 0.5             │
│ Waterstof      ┆ Overig  ┆ Paper  ┆ 2050 ┆ 0.0        ┆ 5580 ┆ 0.38        ┆ 0.5             │
└────────────────┴─────────┴────────┴──────┴────────────┴──────┴─────────────┴─────────────────┘

In [ ]:
curves_production = curves_production.with_columns(pl.col('Cluster').str.to_lowercase().replace('overig', 'Cluster 6').alias('Cluster'))

In [37]:
from constants import ALL_YEARS

all_years  = ALL_YEARS

# sums = curves_production.group_by(['Cluster', 'Sector', 'Scenario', 'Year']
#             ).agg(
#                 [pl.col(i).sum() for i in all_years]
#             ).sort(['Cluster', 'Sector', 'Scenario'])

In [ ]:

groups = {}
for row in curves_production.to_dicts():
    sector = row.get("Sector")
    cluster = row.get("Cluster")
    scenario = row.get("Scenario")
    year = str(row.get("Year"))

    key = (sector, cluster, scenario, year)
        
    if key not in groups:
        # Create a single-row DataFrame for this group
        groups[key] = pl.DataFrame(row).to_dicts()[0]

In [38]:
curves_production.unique(['Cluster', 'Sector', 'Scenario', 'Year'])

shape: (100, 8)
┌──────────────┬───────────┬──────────────┬──────┬────────────┬──────┬──────────────┬──────────────┐
│ Scenario     ┆ Cluster   ┆ Sector       ┆ Year ┆ Capacity   ┆ FLH  ┆ Efficiency   ┆ Efficiency   │
│ ---          ┆ ---       ┆ ---          ┆ ---  ┆ ---        ┆ ---  ┆ electricity  ┆ heat         │
│ str          ┆ str       ┆ str          ┆ i64  ┆ f64        ┆ i64  ┆ ---          ┆ ---          │
│              ┆           ┆              ┆      ┆            ┆      ┆ f64          ┆ f64          │
╞══════════════╪═══════════╪══════════════╪══════╪════════════╪══════╪══════════════╪══════════════╡
│ Waterstof    ┆ Cluster 6 ┆ Food         ┆ 2050 ┆ 0.0        ┆ 5580 ┆ 0.38         ┆ 0.5          │
│ Groen gas    ┆ Cluster 6 ┆ Paper        ┆ 2050 ┆ 0.0        ┆ 5580 ┆ 0.38         ┆ 0.5          │
│ Groen gas    ┆ Cluster 6 ┆ Non metallic ┆ 2040 ┆ 0.189168   ┆ 5580 ┆ 0.38         ┆ 0.5          │
│              ┆           ┆ minerals     ┆      ┆            ┆      ┆              ┆              │
│ Waterstof    ┆ Cluster 6 ┆ Paper        ┆ 2024 ┆ 100.258941 ┆ 5580 ┆ 0.38         ┆ 0.5          │
│ Waterstof    ┆ Cluster 6 ┆ Other        ┆ 2035 ┆ 31.212689  ┆ 5580 ┆ 0.38         ┆ 0.5          │
│              ┆           ┆ chemicals    ┆      ┆            ┆      ┆              ┆              │
│ …            ┆ …         ┆ …            ┆ …    ┆ …          ┆ …    ┆ …            ┆ …            │
│ Midden       ┆ Cluster 6 ┆ Other        ┆ 2024 ┆ 104.042297 ┆ 5580 ┆ 0.38         ┆ 0.5          │
│              ┆           ┆ chemicals    ┆      ┆            ┆      ┆              ┆              │
│ VT           ┆ Cluster 6 ┆ Non metallic ┆ 2050 ┆ 0.0        ┆ 5580 ┆ 0.38         ┆ 0.5          │
│              ┆           ┆ minerals     ┆      ┆            ┆      ┆              ┆              │
│ Midden       ┆ Cluster 6 ┆ Other        ┆ 2035 ┆ 31.212689  ┆ 5580 ┆ 0.38         ┆ 0.5          │
│              ┆           ┆ chemicals    ┆      ┆            ┆      ┆              ┆              │
│ Elektrificat ┆ Cluster 6 ┆ Food         ┆ 2024 ┆ 271.473897 ┆ 5580 ┆ 0.38         ┆ 0.5          │
│ ie           ┆           ┆              ┆      ┆            ┆      ┆              ┆              │
│ Groen gas    ┆ Cluster 6 ┆ Paper        ┆ 2040 ┆ 5.012947   ┆ 5580 ┆ 0.38         ┆ 0.5          │
└──────────────┴───────────┴──────────────┴──────┴────────────┴──────┴──────────────┴──────────────┘

In [30]:
groups

{('Food',
  'Cluster 6',
  'Elektrificatie',
  '2024'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Food', 'Year': 2024, 'Capacity': 271.47389698778494, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Food',
  'Cluster 6',
  'Elektrificatie',
  '2030'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Food', 'Year': 2030, 'Capacity': 190.03172789144944, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Food',
  'Cluster 6',
  'Elektrificatie',
  '2035'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Food', 'Year': 2035, 'Capacity': 81.44216909633548, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Food',
  'Cluster 6',
  'Elektrificatie',
  '2040'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Food', 'Year': 2040, 'Capacity': 13.573694849389248, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Food',
  'Cluster 6',
  'Elektrificatie',
  '2050'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Food', 'Year': 2050, 'Capacity': 0.0, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Elektrificatie',
  '2024'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2024, 'Capacity': 3.7833562724014342, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Elektrificatie',
  '2030'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2030, 'Capacity': 2.6483493906810036, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Elektrificatie',
  '2035'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2035, 'Capacity': 1.1350068817204302, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Elektrificatie',
  '2040'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2040, 'Capacity': 0.18916781362007173, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Elektrificatie',
  '2050'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2050, 'Capacity': 0.0, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Elektrificatie',
  '2024'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2024, 'Capacity': 104.04229749103943, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Elektrificatie',
  '2030'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2030, 'Capacity': 72.8296082437276, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Elektrificatie',
  '2035'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2035, 'Capacity': 31.21268924731183, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Elektrificatie',
  '2040'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2040, 'Capacity': 5.202114874551972, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Elektrificatie',
  '2050'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2050, 'Capacity': 0.0, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Paper',
  'Cluster 6',
  'Elektrificatie',
  '2024'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Paper', 'Year': 2024, 'Capacity': 100.25894121863799, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Paper',
  'Cluster 6',
  'Elektrificatie',
  '2030'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Paper', 'Year': 2030, 'Capacity': 70.18125885304659, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Paper',
  'Cluster 6',
  'Elektrificatie',
  '2035'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Paper', 'Year': 2035, 'Capacity': 30.077682365591393, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Paper',
  'Cluster 6',
  'Elektrificatie',
  '2040'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Paper', 'Year': 2040, 'Capacity': 5.0129470609319, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Paper',
  'Cluster 6',
  'Elektrificatie',
  '2050'): {'Scenario': 'Elektrificatie', 'Cluster': 'Cluster 6', 'Sector': 'Paper', 'Year': 2050, 'Capacity': 0.0, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Midden', '2024'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2024,
  'Capacity': 271.47389698778494,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Midden', '2030'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2030,
  'Capacity': 190.03172789144944,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Midden', '2035'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2035,
  'Capacity': 81.44216909633548,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Midden', '2040'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2040,
  'Capacity': 13.573694849389248,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Midden', '2050'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Midden',
  '2024'): {'Scenario': 'Midden', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2024, 'Capacity': 3.7833562724014342, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Midden',
  '2030'): {'Scenario': 'Midden', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2030, 'Capacity': 2.6483493906810036, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Midden',
  '2035'): {'Scenario': 'Midden', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2035, 'Capacity': 1.1350068817204302, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Midden',
  '2040'): {'Scenario': 'Midden', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2040, 'Capacity': 0.18916781362007173, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Midden',
  '2050'): {'Scenario': 'Midden', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2050, 'Capacity': 0.0, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'Midden', '2024'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2024,
  'Capacity': 104.04229749103943,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'Midden', '2030'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2030,
  'Capacity': 72.8296082437276,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'Midden', '2035'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2035,
  'Capacity': 31.21268924731183,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'Midden', '2040'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2040,
  'Capacity': 5.202114874551972,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'Midden', '2050'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Midden', '2024'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2024,
  'Capacity': 100.25894121863799,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Midden', '2030'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2030,
  'Capacity': 70.18125885304659,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Midden', '2035'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2035,
  'Capacity': 30.077682365591393,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Midden', '2040'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2040,
  'Capacity': 5.0129470609319,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Midden', '2050'): {'Scenario': 'Midden',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'VT', '2024'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2024,
  'Capacity': 271.47389698778494,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'VT', '2030'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2030,
  'Capacity': 190.03172789144944,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'VT', '2035'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2035,
  'Capacity': 81.44216909633548,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'VT', '2040'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2040,
  'Capacity': 13.573694849389248,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'VT', '2050'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Non metallic minerals', 'Cluster 6', 'VT', '2024'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Non metallic minerals',
  'Year': 2024,
  'Capacity': 3.7833562724014342,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Non metallic minerals', 'Cluster 6', 'VT', '2030'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Non metallic minerals',
  'Year': 2030,
  'Capacity': 2.6483493906810036,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Non metallic minerals', 'Cluster 6', 'VT', '2035'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Non metallic minerals',
  'Year': 2035,
  'Capacity': 1.1350068817204302,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Non metallic minerals', 'Cluster 6', 'VT', '2040'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Non metallic minerals',
  'Year': 2040,
  'Capacity': 0.18916781362007173,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Non metallic minerals', 'Cluster 6', 'VT', '2050'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Non metallic minerals',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'VT', '2024'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2024,
  'Capacity': 104.04229749103943,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'VT', '2030'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2030,
  'Capacity': 72.8296082437276,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'VT', '2035'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2035,
  'Capacity': 31.21268924731183,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'VT', '2040'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2040,
  'Capacity': 5.202114874551972,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Other chemicals', 'Cluster 6', 'VT', '2050'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Other chemicals',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'VT', '2024'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2024,
  'Capacity': 100.25894121863799,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'VT', '2030'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2030,
  'Capacity': 70.18125885304659,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'VT', '2035'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2035,
  'Capacity': 30.077682365591393,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'VT', '2040'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2040,
  'Capacity': 5.0129470609319,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'VT', '2050'): {'Scenario': 'VT',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Groen gas', '2024'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2024,
  'Capacity': 271.47389698778494,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Groen gas', '2030'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2030,
  'Capacity': 190.03172789144944,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Groen gas', '2035'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2035,
  'Capacity': 81.44216909633548,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Groen gas', '2040'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2040,
  'Capacity': 13.573694849389248,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Groen gas', '2050'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Groen gas',
  '2024'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2024, 'Capacity': 3.7833562724014342, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Groen gas',
  '2030'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2030, 'Capacity': 2.6483493906810036, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Groen gas',
  '2035'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2035, 'Capacity': 1.1350068817204302, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Groen gas',
  '2040'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2040, 'Capacity': 0.18916781362007173, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Non metallic minerals',
  'Cluster 6',
  'Groen gas',
  '2050'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Non metallic minerals', 'Year': 2050, 'Capacity': 0.0, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Groen gas',
  '2024'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2024, 'Capacity': 104.04229749103943, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Groen gas',
  '2030'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2030, 'Capacity': 72.8296082437276, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Groen gas',
  '2035'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2035, 'Capacity': 31.21268924731183, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Groen gas',
  '2040'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2040, 'Capacity': 5.202114874551972, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Other chemicals',
  'Cluster 6',
  'Groen gas',
  '2050'): {'Scenario': 'Groen gas', 'Cluster': 'Cluster 6', 'Sector': 'Other chemicals', 'Year': 2050, 'Capacity': 0.0, 'FLH': 5580, 'Efficiency electricity': 0.38, 'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Groen gas', '2024'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2024,
  'Capacity': 100.25894121863799,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Groen gas', '2030'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2030,
  'Capacity': 70.18125885304659,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Groen gas', '2035'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2035,
  'Capacity': 30.077682365591393,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Groen gas', '2040'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2040,
  'Capacity': 5.0129470609319,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Paper', 'Cluster 6', 'Groen gas', '2050'): {'Scenario': 'Groen gas',
  'Cluster': 'Cluster 6',
  'Sector': 'Paper',
  'Year': 2050,
  'Capacity': 0.0,
  'FLH': 5580,
  'Efficiency electricity': 0.38,
  'Efficiency heat': 0.5},
 ('Food', 'Cluster 6', 'Waterstof', '2024'): {'Scenario': 'Waterstof',
  'Cluster': 'Cluster 6',
  'Sector': 'Food',
  'Year': 2024,