In [28]:
import polars as pl
import pandas as pd
import json

In [29]:
DATA_FILES = {
    "emission_forecast": "datasafehouse-emission-forecast-export_all_v3_20260709live.csv",
    "demand_forecast": "datasafehouse-forecast-export_all_v3_20260709live.csv",
    "emission_reference": "reference_emission_data_20260709live.csv",
    "demand_reference": "reference_utility_data_20260709live.csv",
    "plants": "datasafehouse-plant-export_20260709live.csv",
    "project_emissions": "datasafehouse-projectdata-export_emissions_20260709live.csv",
    "project_utilities": "datasafehouse-projectdata-export_utilities_20260709live.csv",
    "production": "data-export_electricity_production_20260709live.csv",
    "storage": "data-export_energy_storage_20260709live.csv",
    "flexibility": "data-export_flex_options_20260709live.csv",
}

DATA_DIR = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/dsh/20260709_live DSH exports'

def parse_All_EANs(df: pl.DataFrame) -> pl.DataFrame:
    """Expands the 'All EANs' JSON column into multiple rows/columns."""
    df_pd = df.to_pandas()
    df_pd['All EANs'] = df_pd['All EANs'].apply(json.loads)
    df_pd = df_pd.explode('All EANs', ignore_index=True)
    ean_df = pd.json_normalize(df_pd['All EANs'])
    df_pd = pd.concat([df_pd.drop('All EANs', axis=1), ean_df], axis=1)
    return pl.from_pandas(df_pd)

def read_csv(filename: str) -> pl.DataFrame:
    """Read a CSV via pandas, falling back to Polars for malformed files."""
    filepath = f"{DATA_DIR}/{filename}"
    try:
        return pl.from_pandas(pd.read_csv(filepath))
    except pd.errors.ParserError:
        print(f"  [warn] Falling back to Polars for {filename}")
        return pl.read_csv(filepath, truncate_ragged_lines=True)
 
 
def load_data() -> dict[str, pl.DataFrame]:
    """Load all source CSVs and return as a named dict."""
    print("Loading data...")
    data = {name: read_csv(filename) for name, filename in DATA_FILES.items()}
    # Parse EANs once here so it's not repeated per plant
    data["plants_parsed"] = parse_All_EANs(data["plants"])
    print(f"  Loaded {len(DATA_FILES)} files.")
    return data

In [30]:
data = load_data()

Loading data...
  [warn] Falling back to Polars for data-export_electricity_production_20260709live.csv
  [warn] Falling back to Polars for data-export_flex_options_20260709live.csv
  Loaded 10 files.

In [31]:
YEARS = ['2024', '2030', '2035', '2040', '2050']
SCENARIO_YEARS = ['2030', '2035', '2040', '2050']
REF_YEAR = '2024'

In [32]:
data['plants'] = data['plants'].select(['Plant name', 'Plant identifier'])

In [33]:
data['emission_reference'] = (
    data['emission_reference'].select(
    ['Plant', 'Plant identifier', 'Cluster','Emission', 'Year', 'Annual amount'])
    .filter(pl.col('Year').cast(pl.Utf8) == REF_YEAR)
    .rename({'Annual amount' : 'Value'})
    .pivot('Emission', index=['Plant identifier', 'Plant', 'Cluster', 'Year'], values='Value')
    .with_columns(pl.col('Year').cast(pl.Utf8))
    .with_columns(pl.lit("Reference").alias("Scenario"))
    .with_columns(pl.lit('production').alias('Flow type'))
    .with_columns(
                (pl.col("NOx").cast(pl.Float64).fill_null(0.0) 
                 + pl.col("N2O").cast(pl.Float64).fill_null(0.0)
                 ).alias("N2O")
            )
    .drop(['NOx'])
    .rename({'Plant':'Plant name'})
)

In [34]:
data['emission_forecast'] = (
    data['emission_forecast'].drop(['Company', 'Version date'])
    .unpivot(SCENARIO_YEARS, index = ['Plant name', 'Plant identifier', 'Scenario', 'Emission'], variable_name='Year', value_name='Value')
    .pivot('Emission', index=['Plant identifier', 'Plant name', 'Scenario', 'Year'], values='Value')
    .with_columns(pl.lit('production').alias('Flow type'))
    .with_columns(
                    (pl.col("NOx").cast(pl.Float64).fill_null(0.0) 
                        + pl.col("N₂O").cast(pl.Float64).fill_null(0.0)
                        ).alias("N2O")
                )
        .drop(['NOx', 'N₂O'])
        )

In [35]:
data['emission_reference'].schema

Schema([('Plant identifier', String),
        ('Plant name', String),
        ('Cluster', String),
        ('Year', String),
        ('CO2', Float64),
        ('N2O', Float64),
        ('Scenario', String),
        ('Flow type', String)])

In [36]:
data['emission_forecast'].schema

Schema([('Plant identifier', String),
        ('Plant name', String),
        ('Scenario', String),
        ('Year', String),
        ('CO2', Float64),
        ('Methane', Float64),
        ('F-gases', Float64),
        ('other', Float64),
        ('Flow type', String),
        ('N2O', Float64)])

In [37]:
result = pl.concat(
    [data['emission_reference'], data['emission_forecast']],
    how="diagonal_relaxed",
)

result

shape: (1_295, 11)
┌───────────────┬───────────────┬──────────────┬──────┬───┬────────────┬─────────┬─────────┬───────┐
│ Plant         ┆ Plant name    ┆ Cluster      ┆ Year ┆ … ┆ Flow type  ┆ Methane ┆ F-gases ┆ other │
│ identifier    ┆ ---           ┆ ---          ┆ ---  ┆   ┆ ---        ┆ ---     ┆ ---     ┆ ---   │
│ ---           ┆ str           ┆ str          ┆ str  ┆   ┆ str        ┆ f64     ┆ f64     ┆ f64   │
│ str           ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
╞═══════════════╪═══════════════╪══════════════╪══════╪═══╪════════════╪═════════╪═════════╪═══════╡
│ 527be9a2-5258 ┆ ADM Europoort ┆ Rotterdam-Mo ┆ 2024 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -4cda-89cb-b4 ┆               ┆ erdijk       ┆      ┆   ┆            ┆         ┆         ┆       │
│ 8520…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 18ada8d6-9982 ┆ Alco Energy   ┆ Rotterdam-Mo ┆ 2024 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -4647-a80b-90 ┆ Europoort     ┆ erdijk       ┆      ┆   ┆            ┆         ┆         ┆       │
│ fb14…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ cb69c2cf-c121 ┆ ExxonMobil    ┆ Rotterdam-Mo ┆ 2024 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -46d5-84a3-35 ┆ Raffinaderij  ┆ erdijk       ┆      ┆   ┆            ┆         ┆         ┆       │
│ ea3b…         ┆ Botlek        ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 3607cefd-8e6c ┆ Lyondell      ┆ Rotterdam-Mo ┆ 2024 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -4943-8878-2e ┆ Botlek        ┆ erdijk       ┆      ┆   ┆            ┆         ┆         ┆       │
│ 2cc7…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ c00446f2-df0c ┆ Nobian Botlek ┆ Rotterdam-Mo ┆ 2024 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -466d-a5c9-82 ┆               ┆ erdijk       ┆      ┆   ┆            ┆         ┆         ┆       │
│ f434…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ …             ┆ …             ┆ …            ┆ …    ┆ … ┆ …          ┆ …       ┆ …       ┆ …     │
│ 9f81eb85-64e2 ┆ Yara Sluiskil ┆ null         ┆ 2050 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -44ed-8f85-be ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ b6a9…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 401a65fd-5228 ┆ Zeeland       ┆ null         ┆ 2050 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -47d2-ae6a-96 ┆ Refinery      ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 22a8…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 401a65fd-5228 ┆ Zeeland       ┆ null         ┆ 2050 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -47d2-ae6a-96 ┆ Refinery      ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 22a8…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 401a65fd-5228 ┆ Zeeland       ┆ null         ┆ 2050 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -47d2-ae6a-96 ┆ Refinery      ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 22a8…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 401a65fd-5228 ┆ Zeeland       ┆ null         ┆ 2050 ┆ … ┆ production ┆ null    ┆ null    ┆ null  │
│ -47d2-ae6a-96 ┆ Refinery      ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
│ 22a8…         ┆               ┆              ┆      ┆   ┆            ┆         ┆         ┆       │
└───────────────┴───────────────┴──────────────┴──────┴───┴────────────┴─────────┴─────────┴───────┘

In [38]:
type(data)

dict

In [39]:
"""
Build master wide-format table from DSH data files.
"""

import polars as pl
from typing import Dict


def build_master_table(data: Dict[str, pl.DataFrame]) -> pl.DataFrame:
    """
    Build master table from DSH forecasts and reference data.
    
    Wide format:
    Company | Cluster | Sector | Scenario | Year | Type | CO2 | Methane | ... | Electricity | Natural Gas | ...
    
    Args:
        data: Dict with keys: emission_forecast, demand_forecast, 
              emission_reference, demand_reference, plants
    
    Returns:
        Master DataFrame in wide format
    """
    
    # ── Step 1: Get cluster/sector from reference data ─────────────────
    # Get unique company-cluster-plant pairs
    ref_meta = data["demand_reference"].select([
        "Plant identifier", "Company", "Cluster"
    ]).unique()
    
    # Rename SBI to Sector (or create from SBI code if needed)
    # ref_meta = ref_meta.rename({"SBI (2008)": "Sector"})
    
    # ── Step 2: Reshape emission forecast ──────────────────────────────
    # Pivot years to long format, then pivot Emission to wide
    emission_long = data["emission_forecast"].unpivot(
        index=["Plant identifier", "Company", "Scenario", "Emission"],
        variable_name="Year",
        value_name="Value"
    )
    
    # Convert Year to int
    # emission_long = emission_long.with_columns(
    #     pl.col("Year").cast(pl.Utf8).str.to_integer().cast(pl.Int64)
    # )
    
    # Pivot Emission types to columns (CO2, Methane, etc)
    emission_wide = emission_long.pivot(
        index=["Plant identifier", "Company", "Scenario", "Year"],
        columns="Emission",
        values="Value",
        aggregate_function="first"
    )
    
    # ── Step 3: Reshape demand forecast ────────────────────────────────
    # Pivot years to long format
    demand_long = data["demand_forecast"].unpivot(
        index=["Plant identifier", "Company", "Scenario", "Utility", "Flow type"],
        variable_name="Year",
        value_name="Value"
    )
    
    # Convert Year to int
    # demand_long = demand_long.with_columns(
    #     pl.col("Year").cast(pl.Utf8).str.to_integer().cast(pl.Int64)
    # )
    
    # Rename "Flow type" to "Type"
    demand_long = demand_long.rename({"Flow type": "Type"})
    
    # Pivot Utilities to columns (Electricity, Natural Gas, etc)
    demand_wide = demand_long.pivot(
        index=["Plant identifier", "Company", "Scenario", "Year", "Type"],
        columns="Utility",
        values="Value",
        aggregate_function="first"
    )
    
    # ── Step 4: Join emissions + demands ───────────────────────────────
    # Merge on Plant identifier, Company, Scenario, Year
    master = emission_wide.join(
        demand_wide,
        on=["Plant identifier", "Company", "Scenario", "Year"],
        how="outer"
    ).drop("Company_right")
    
    # ── Step 5: Add cluster/sector metadata ────────────────────────────
    master = master.join(
        ref_meta,
        on="Plant identifier",
        how="left"
    )
    
    # Handle duplicate Company columns (keep the one from ref_meta)
    if master.columns.count("Company") > 1:
        master = master.drop("Company_right").rename({"Company_left": "Company"})
    
    # ── Step 6: Reorder columns ────────────────────────────────────────
    # Priority: Company, Cluster, Sector, Scenario, Year, Type, then data columns
    base_cols = ["Company", "Cluster", "Sector", "Scenario", "Year", "Type"]
    data_cols = [c for c in master.columns if c not in base_cols + ["Plant identifier"]]
    
    final_cols = base_cols + data_cols + ["Plant identifier"]
    
    # Only keep columns that exist
    final_cols = [c for c in final_cols if c in master.columns]
    
    master = master.select(final_cols)
    
    # ── Step 7: Sort for readability ───────────────────────────────────
    master = master.sort(["Company", "Scenario", "Year", "Type"])
    
    return master

In [40]:
# master = build_master_table(data)
# master.write_csv("master_table.csv")
# st.dataframe(master)

In [41]:
# master

In [42]:
from read_DSH_files import read_all_scenario_sheets
from push_to_ctm_modules import load_all_plants_scenario_data
from constants import EMISSION_COLS_ORDER, UTILITY_COLS_ORDER

test_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/Sprint 2 CTM upload/Cargill Bergen op Zoom.xlsx'

test_plant = test_path.split('/')[-1].split('.')[0]

test = read_all_scenario_sheets(
    workbook_path=test_path,
    emission_cols=EMISSION_COLS_ORDER,
    energy_cols=UTILITY_COLS_ORDER,
    reference_year=REF_YEAR,
    aggregate_flow_types=False
)

In [43]:
aux_details = data['emission_reference'].filter(pl.col('Plant name') == test_plant)
aux_details

shape: (1, 8)
┌─────────────────┬─────────────────┬─────────────────┬──────┬──────┬─────┬───────────┬────────────┐
│ Plant           ┆ Plant name      ┆ Cluster         ┆ Year ┆ CO2  ┆ N2O ┆ Scenario  ┆ Flow type  │
│ identifier      ┆ ---             ┆ ---             ┆ ---  ┆ ---  ┆ --- ┆ ---       ┆ ---        │
│ ---             ┆ str             ┆ str             ┆ str  ┆ f64  ┆ f64 ┆ str       ┆ str        │
│ str             ┆                 ┆                 ┆      ┆      ┆     ┆           ┆            │
╞═════════════════╪═════════════════╪═════════════════╪══════╪══════╪═════╪═══════════╪════════════╡
│ 8848af70-221e-4 ┆ Cargill Bergen  ┆ Zeeland-West-Br ┆ 2024 ┆ 44.5 ┆ 0.0 ┆ Reference ┆ production │
│ 489-b24e-565e00 ┆ op Zoom         ┆ abant           ┆      ┆      ┆     ┆           ┆            │
│ …               ┆                 ┆                 ┆      ┆      ┆     ┆           ┆            │
└─────────────────┴─────────────────┴─────────────────┴──────┴──────┴─────┴───────────┴────────────┘

In [44]:
cluster = aux_details.select(pl.col('Cluster'))[0].item()
cluster

'Zeeland-West-Brabant'

In [45]:
aux_ref = data['emission_reference'].select(['Scenario', 'Year', 'Flow type', 'CO2', 'N2O'])
aux_ref

shape: (47, 5)
┌───────────┬──────┬────────────┬─────────┬──────────┐
│ Scenario  ┆ Year ┆ Flow type  ┆ CO2     ┆ N2O      │
│ ---       ┆ ---  ┆ ---        ┆ ---     ┆ ---      │
│ str       ┆ str  ┆ str        ┆ f64     ┆ f64      │
╞═══════════╪══════╪════════════╪═════════╪══════════╡
│ Reference ┆ 2024 ┆ production ┆ 135.297 ┆ 0.0      │
│ Reference ┆ 2024 ┆ production ┆ 348.0   ┆ 0.0      │
│ Reference ┆ 2024 ┆ production ┆ 2182.0  ┆ 0.0      │
│ Reference ┆ 2024 ┆ production ┆ 290.653 ┆ 0.0      │
│ Reference ┆ 2024 ┆ production ┆ 103.0   ┆ 0.0      │
│ …         ┆ …    ┆ …          ┆ …       ┆ …        │
│ Reference ┆ 2024 ┆ production ┆ 147.0   ┆ 0.0      │
│ Reference ┆ 2024 ┆ production ┆ null    ┆ 0.0      │
│ Reference ┆ 2024 ┆ production ┆ 219.835 ┆ 0.098282 │
│ Reference ┆ 2024 ┆ production ┆ 12.0    ┆ 0.0      │
│ Reference ┆ 2024 ┆ production ┆ 11120.0 ┆ 0.0      │
└───────────┴──────┴────────────┴─────────┴──────────┘

In [46]:
def process_demand_reference(df: pl.DataFrame) -> pl.DataFrame:
    """
    Process demand_reference to match scenario data schema.
    
    Converts:
    - Year: Int64 → String
    - Creates Flow type column from Annual demand/supply/production/captive use
    - Pivots utilities to columns
    
    Returns same schema as scenario sheets:
    Plant identifier, Plant name, Cluster, Year, <utilities>, Scenario, Flow type
    """
    
    # Convert Year to String
    df = df.with_columns(
        pl.col("Year").cast(pl.Utf8)
    )
    
    # Create long format with different flow types
    demand_rows = df.select([
        "Plant identifier", "Plant", "Cluster", "Year", "Utility",
        pl.lit("demand").alias("Flow type"),
        pl.lit("Reference").alias("Scenario"),
        pl.col("Annual demand").alias("Value"),
    ]).filter(pl.col("Value").is_not_null())
    
    supply_rows = df.select([
        "Plant identifier", "Plant", "Cluster", "Year", "Utility",
        pl.lit("supply").alias("Flow type"),
        pl.lit("Reference").alias("Scenario"),
        pl.col("Annual supply").alias("Value"),
    ]).filter(pl.col("Value").is_not_null())
    
    production_rows = df.select([
        "Plant identifier", "Plant", "Cluster", "Year", "Utility",
        pl.lit("production").alias("Flow type"),
        pl.lit("Reference").alias("Scenario"),
        pl.col("Annual production").alias("Value"),
    ]).filter(pl.col("Value").is_not_null())
    
    captive_rows = df.select([
        "Plant identifier", "Plant", "Cluster", "Year", "Utility",
        pl.lit("captive use").alias("Flow type"),
        pl.lit("Reference").alias("Scenario"),
        pl.col("Captive use annual").alias("Value"),
    ]).filter(pl.col("Value").is_not_null())
    
    # Combine all flow types
    combined = pl.concat([demand_rows, supply_rows, production_rows, captive_rows])
    
    # Pivot utilities to columns (like scenario data)
    pivoted = combined.pivot(
        index=["Plant identifier", "Plant", "Cluster", "Year", "Scenario", "Flow type"],
        columns="Utility",
        values="Value",
        aggregate_function="first"
    )
    
    # Rename "Plant" to "Plant name" for consistency
    pivoted = pivoted.rename({"Plant": "Plant name"})
    
    # Reorder columns: Plant identifier, Plant name, Cluster, Year, <utilities>, Scenario, Flow type
    base_cols = ["Plant identifier", "Plant name", "Cluster", "Year"]
    utility_cols = [c for c in pivoted.columns if c not in base_cols + ["Scenario", "Flow type"]]
    final_cols = base_cols + utility_cols + ["Scenario", "Flow type"]
    
    return pivoted.select(final_cols)

In [47]:
data["demand_reference_processed"] = process_demand_reference(data["demand_reference"])

/tmp/ipykernel_925441/1109463735.py:52: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  pivoted = combined.pivot(

In [48]:
data["demand_reference_processed"]

shape: (263, 20)
┌────────────┬────────────┬────────────┬──────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Plant      ┆ Plant name ┆ Cluster    ┆ Year ┆ … ┆ CO2 (bio)  ┆ CO2       ┆ Scenario  ┆ Flow type │
│ identifier ┆ ---        ┆ ---        ┆ ---  ┆   ┆ CCU/CCS    ┆ (fossil)  ┆ ---       ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str  ┆   ┆ ---        ┆ CCU/CCS   ┆ str       ┆ str       │
│ str        ┆            ┆            ┆      ┆   ┆ f64        ┆ ---       ┆           ┆           │
│            ┆            ┆            ┆      ┆   ┆            ┆ f64       ┆           ┆           │
╞════════════╪════════════╪════════════╪══════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 6beec4ef-2 ┆ Chane      ┆ Noordzeeka ┆ 2024 ┆ … ┆ null       ┆ null      ┆ Reference ┆ demand    │
│ 63a-418f-a ┆ Terminal   ┆ naalgebied ┆      ┆   ┆            ┆           ┆           ┆           │
│ 992-34ad7a ┆ Zaandam    ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ (CTZA)     ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ ec1ffca3-e ┆ Chane      ┆ Rotterdam- ┆ 2022 ┆ … ┆ null       ┆ null      ┆ Reference ┆ demand    │
│ 31f-4b8c-b ┆ Terminal   ┆ Moerdijk   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 466-681151 ┆ Pernis     ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ (CTPE)     ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ ec1ffca3-e ┆ Chane      ┆ Rotterdam- ┆ 2024 ┆ … ┆ null       ┆ null      ┆ Reference ┆ demand    │
│ 31f-4b8c-b ┆ Terminal   ┆ Moerdijk   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 466-681151 ┆ Pernis     ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ (CTPE)     ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ ec1ffca3-e ┆ Chane      ┆ Rotterdam- ┆ 2021 ┆ … ┆ null       ┆ null      ┆ Reference ┆ demand    │
│ 31f-4b8c-b ┆ Terminal   ┆ Moerdijk   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 466-681151 ┆ Pernis     ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ (CTPE)     ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ 277ed4ca-c ┆ AsfaltNU   ┆ Noordzeeka ┆ 2023 ┆ … ┆ null       ┆ null      ┆ Reference ┆ demand    │
│ e15-4bd9-b ┆ ANA II     ┆ naalgebied ┆      ┆   ┆            ┆           ┆           ┆           │
│ 026-b322ed ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …    ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2ea6230e-8 ┆ Ketjen CMF ┆ Noordzeeka ┆ 2021 ┆ … ┆ null       ┆ null      ┆ Reference ┆ captive   │
│ e15-4765-b ┆            ┆ naalgebied ┆      ┆   ┆            ┆           ┆           ┆ use       │
│ 40e-b2d20c ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ 2ea6230e-8 ┆ Ketjen CMF ┆ Noordzeeka ┆ 2024 ┆ … ┆ null       ┆ null      ┆ Reference ┆ captive   │
│ e15-4765-b ┆            ┆ naalgebied ┆      ┆   ┆            ┆           ┆           ┆ use       │
│ 40e-b2d20c ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ 42aec4bc-d ┆ EEW        ┆ Noord-Nede ┆ 2024 ┆ … ┆ null       ┆ null      ┆ Reference ┆ captive   │
│ 7a6-44b1-8 ┆ Delfzijl   ┆ rland      ┆      ┆   ┆            ┆           ┆           ┆ use       │
│ 427-cf8360 ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ d4cec76a-4 ┆ ExxonMobil ┆ Rotterdam- ┆ 2021 ┆ … ┆ null       ┆ null      ┆ Reference ┆ captive   │
│ 286-4d63-b ┆ Europoort  ┆ Moerdijk   ┆      ┆   ┆            ┆           ┆           ┆ use       │
│ 2c6-539132 ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ 527be9a2-5 ┆ ADM        ┆ Rotterdam- ┆ 2024 ┆ … ┆ null       ┆ null      ┆ Reference ┆ captive   │
│ 258-4cda-8 ┆ Europoort  ┆ Moerdijk   ┆      ┆   ┆            ┆           ┆           ┆ use       │
│ 9cb-b48520 ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴──────┴───┴────────────┴───────────┴───────────┴───────────┘

In [49]:

from openpyxl import load_workbook

def read_all_scenario_sheets_from_excels(
    excel_files_dict: Dict[str, bytes],
    emission_cols: list[str],
    energy_cols: list[str],
    reference_year: int = 2024,
) -> pl.DataFrame:
    """
    Read all Scenario X sheets from all generated Excel files.
    Returns combined DataFrame with plant name from filename.
    """
    
    import tempfile
    from pathlib import Path
    
    all_records = []
    
    for file_name, file_bytes in excel_files_dict.items():
        # Extract plant name from filename (e.g., "Plant A.xlsx" → "Plant A")
        plant_name = Path(file_name).stem
        
        # Save to temp file
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(file_bytes)
            tmp_path = tmp.name
        
        try:
            wb = load_workbook(tmp_path, data_only=True)
            
            # Read each Scenario sheet
            for sheet_name in wb.sheetnames:
                if not sheet_name.startswith("Scenario"):
                    continue
                
                df = read_all_scenario_sheets(
                    workbook_path=tmp_path,
                    sheet_name=sheet_name,
                    emission_cols=emission_cols,
                    energy_cols=energy_cols,
                    reference_year=reference_year,
                )
                
                if not df.is_empty():
                    # Add plant name column
                    df = df.with_columns(
                        pl.lit(plant_name).alias("Plant name")
                    )
                    all_records.append(df)
        
        finally:
            Path(tmp_path).unlink()  # Clean up temp file
    
    if all_records:
        return pl.concat(all_records)
    else:
        return pl.DataFrame()

In [50]:
def build_master_table_combined(
    scenario_data: pl.DataFrame,  # From Excel files (has Scenario, Year, Flow type, utilities, emissions)
    emission_reference: pl.DataFrame,  # Already processed
    demand_reference: pl.DataFrame,  # Already processed (processed_demand_reference)
    plant_meta: pl.DataFrame,  # For enriching scenario data with Plant identifier, Cluster
) -> pl.DataFrame:
    """
    Combine scenario data, emission reference, and demand reference into one master table.
    
    Args:
        scenario_data: DataFrame from reading Excel scenario sheets
        emission_reference: Processed emission reference data
        demand_reference: Processed demand reference data (from process_demand_reference)
        plant_meta: DataFrame with Plant name, Plant identifier, Cluster mapping
    
    Returns:
        Master table with all data combined
    """
    
    # ── Part 1: Enrich scenario data with plant metadata ────────────────
    # Scenario data needs: Plant identifier, Plant name, Cluster
    # (assuming it comes from a specific Excel file, so we know the plant)
    
    scenario_enriched = scenario_data.join(
        plant_meta.select(["Plant name", "Plant identifier", "Cluster"]),
        left_on="Plant name",  # or however plant is identified in Excel
        right_on="Plant name",
        how="left"
    )
    
    # Reorder scenario columns to match reference data
    base_cols = ["Plant identifier", "Plant name", "Cluster", "Year", "Scenario", "Flow type"]
    data_cols = [c for c in scenario_enriched.columns if c not in base_cols]
    scenario_enriched = scenario_enriched.select(base_cols + data_cols)
    
    # ── Part 2: Standardize all three dataframes ───────────────────────
    # Find all unique columns across all three
    all_cols = set(scenario_enriched.columns) | set(emission_reference.columns) | set(demand_reference.columns)
    
    # Common base columns
    base_cols = ["Plant identifier", "Plant name", "Cluster", "Year", "Scenario", "Flow type"]
    
    # Data columns (metrics)
    metric_cols = sorted([c for c in all_cols if c not in base_cols])
    
    # Fill missing columns with null
    for df in [scenario_enriched, emission_reference, demand_reference]:
        for col in metric_cols:
            if col not in df.columns:
                df = df.with_columns(pl.lit(None).cast(pl.Float64).alias(col))
    
    # ── Part 3: Concatenate all three ──────────────────────────────────
    master = pl.concat(
        [scenario_enriched, emission_reference, demand_reference],
        how="diagonal_relaxed"  # Handles different column sets
    )
    
    # ── Part 4: Reorder and sort ───────────────────────────────────────
    final_cols = base_cols + metric_cols
    final_cols = [c for c in final_cols if c in master.columns]
    
    master = master.select(final_cols)
    
    # Sort for readability
    master = master.sort_by(["Plant name", "Scenario", "Year", "Flow type"])
    
    return master

In [51]:
EXCEL_FOLDER = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/Sprint 2 CTM upload'
from pathlib import Path

excel_folder = Path(EXCEL_FOLDER)
excel_files = list(excel_folder.glob("*.xlsx"))
 
print(f"Found {len(excel_files)} Excel files")
 
all_scenario_records = []
 
for excel_path in excel_files:  # Test with first 5 files
    plant_name = excel_path.stem
    print(f"  Reading: {plant_name}")
    
    try:
        wb = load_workbook(excel_path, data_only=True)
        
           
        df = read_all_scenario_sheets(
            workbook_path=str(excel_path),
            emission_cols=EMISSION_COLS_ORDER,
            energy_cols=UTILITY_COLS_ORDER,
            reference_year='0',
            aggregate_flow_types=False, 
        )

        reference = df.filter(
            pl.col("Year") == str(REF_YEAR)
        )
        
        # Set Scenario to 'Reference'
        reference = reference.with_columns(
            pl.lit("Reference").alias("Scenario")
        )
        
        # Remove duplicates (same plant, year, flow_type should have same metric values)
        reference = reference.unique(
            subset=["Scenario", "Year", "Flow type"],
            keep="first"
        )

        scenario_data = df.filter(pl.col("Year") != "2024")

        # Combine
        master = pl.concat([scenario_data, reference])

        if not master.is_empty():
            # Add plant name
            master = master.with_columns(
                pl.lit(plant_name).alias("Plant name")
            )
            all_scenario_records.append(master)
            
    
    except Exception as e:
        print(f"    [ERROR] {e}")
 
if all_scenario_records:
    scenario_data = pl.concat(all_scenario_records, how='vertical_relaxed')
    print(f"Combined scenario data: {scenario_data.shape}")
    print(f"Columns: {scenario_data.columns}")
else:
    print("No scenario data found!")
    scenario_data = pl.DataFrame()

Found 46 Excel files
  Reading: Air Liquide Bergen op Zoom
  Reading: Air Liquide Booster Moerdijk
  Reading: Air Liquide Moerdijk
  Reading: ADM Europoort
  Reading: Air Liquide Pernis
  Reading: Air Liquide Rozenburg (Botlek)
  Reading: Air Liquide Terneuzen
  Reading: Air Products locatie Botlekweg (HyCO)
  Reading: Air Products locatie Merseyweg (ASUs)
  Reading: Alco Energy Europoort
  Reading: AsfaltNU ANA I
  Reading: Cargill Aurora
  Reading: AsfaltNU ANA II
  Reading: Cabot Botlek
  Reading: Cargill Botlek
  Reading: Cargill Jonker
  Reading: Cargill Bergen op Zoom
  Reading: Cargill Multiseeds
  Reading: Cargill ZOR
  Reading: Delfzijl Nieuw
  Reading: CiC Chemport Innovation Center
  Reading: Dow Delfzijl
  Reading: ExxonMobil Raffinaderij Botlek
  Reading: ExxonMobil Europoort
  Reading: Forbo Flooring BV
  Reading: Huntsman Botlek
  Reading: Getec Park Emmen
  Reading: Ketjen CMF
  Reading: Lanxess Botlek
  Reading: LW Bergen op Zoom
  Reading: LW Kruiningen
  Reading: Lyondell Botlek
  Reading: LyondellBasell Moerdijk
  Reading: Nobian Botlek
  Reading: Qemetica Delfzijl
  Reading: SABIC Bergen op Zoom
  Reading: Overig Chemelot Geleen
  Reading: Shell Pernis
  Reading: Shell Chemie Moerdijk
  Reading: Shin-Etsu Botlek VCM fabriek
  Reading: Shin-Etsu Pernis PVC fabriek
  Reading: Synthomer Middelburg
  Reading: Sonneborn Refined Products Amsterdam
  Reading: Tata Steel
  Reading: Yara Sluiskil
  Reading: Zeeland Refinery
Combined scenario data: (3864, 28)
Columns: ['Scenario', 'Year', 'Flow type', 'CO2', 'Methane', 'N2O', 'F-gases', 'CO2 (fossil) CCU/CCS', 'CO2 (bio) CCU/CCS', 'Electricity', 'Electricity_peak', 'Natural Gas', 'Hydrogen ( >98% vol.%) (LHV)', 'Hydrogen ( <98% vol.%) (LHV)', 'Heat', 'Residual gases', 'Coal and coal products', 'Oil and oil products', 'Biomass (liquid)', 'Biomass (solid)', 'Green gas', 'Waste (fossil)', 'Waste (bio)', 'Ammonia', 'Methanol', 'Other syn fuel and raw materials', 'Other', 'Plant name']

In [52]:
scenario_data

shape: (3_864, 28)
┌───────────┬──────┬─────────────┬────────┬───┬──────────┬────────────────┬───────┬────────────────┐
│ Scenario  ┆ Year ┆ Flow type   ┆ CO2    ┆ … ┆ Methanol ┆ Other syn fuel ┆ Other ┆ Plant name     │
│ ---       ┆ ---  ┆ ---         ┆ ---    ┆   ┆ ---      ┆ and raw        ┆ ---   ┆ ---            │
│ str       ┆ str  ┆ str         ┆ f64    ┆   ┆ f64      ┆ materia…       ┆ i64   ┆ str            │
│           ┆      ┆             ┆        ┆   ┆          ┆ ---            ┆       ┆                │
│           ┆      ┆             ┆        ┆   ┆          ┆ f64            ┆       ┆                │
╞═══════════╪══════╪═════════════╪════════╪═══╪══════════╪════════════════╪═══════╪════════════════╡
│ Midden    ┆ 2030 ┆ demand      ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Air Liquide    │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Bergen op Zoom │
│ Midden    ┆ 2030 ┆ captive use ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Air Liquide    │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Bergen op Zoom │
│ Midden    ┆ 2030 ┆ production  ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Air Liquide    │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Bergen op Zoom │
│ Midden    ┆ 2030 ┆ supply      ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Air Liquide    │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Bergen op Zoom │
│ Midden    ┆ 2035 ┆ demand      ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Air Liquide    │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Bergen op Zoom │
│ …         ┆ …    ┆ …           ┆ …      ┆ … ┆ …        ┆ …              ┆ …     ┆ …              │
│ VT        ┆ 2050 ┆ supply      ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0            ┆ null  ┆ Zeeland        │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Refinery       │
│ Reference ┆ 2024 ┆ production  ┆ 1528.0 ┆ … ┆ null     ┆ null           ┆ null  ┆ Zeeland        │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Refinery       │
│ Reference ┆ 2024 ┆ demand      ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Zeeland        │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Refinery       │
│ Reference ┆ 2024 ┆ captive use ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Zeeland        │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Refinery       │
│ Reference ┆ 2024 ┆ supply      ┆ null   ┆ … ┆ null     ┆ null           ┆ null  ┆ Zeeland        │
│           ┆      ┆             ┆        ┆   ┆          ┆                ┆       ┆ Refinery       │
└───────────┴──────┴─────────────┴────────┴───┴──────────┴────────────────┴───────┴────────────────┘

In [53]:
# mapping = pl.read_csv('/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/mapping.csv')
from utils import read_and_transform_mapping

map_path = '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/ctm/input/20260630 sprint 2 CTM-DSH site mapping.xlsx'

mapping = read_and_transform_mapping(
    excel_path=map_path, 
    save_file=False,
    normalize_sector_cluster=True

)

Could not determine dtype for column 4, falling back to string

Session created: SE-a36c49848deb095c
Clean sheet applied.
Loading all arguments...
Session deleted: SE-a36c49848deb095c successfully deleted!

In [54]:
mapping_subset = mapping.select([
        "DSH plant name",
        "Cluster",
        "Sector",
    ]).unique()
    
# Join on plant name
df_enriched = scenario_data.join(
    mapping_subset,
    left_on='Plant name',
    right_on="DSH plant name",
    how="left"
)

# Drop DSH plant name (duplicate)
if "DSH plant name" in df_enriched.columns:
    df_enriched = df_enriched.drop("DSH plant name")

# Reorder: Cluster and Sector after plant info, before metrics
base_cols = ["Plant name", "Cluster", "Sector", "Scenario", "Year", "Flow type"]
metric_cols = [c for c in df_enriched.columns if c not in base_cols]

df_enriched = df_enriched.select(base_cols + metric_cols)

In [55]:
df_enriched.sort(['Plant name', 'Year', 'Flow type'])

shape: (3_864, 30)
┌─────────────┬────────────┬────────────┬────────────┬───┬─────────┬──────────┬────────────┬───────┐
│ Plant name  ┆ Cluster    ┆ Sector     ┆ Scenario   ┆ … ┆ Ammonia ┆ Methanol ┆ Other syn  ┆ Other │
│ ---         ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---     ┆ ---      ┆ fuel and   ┆ ---   │
│ str         ┆ str        ┆ str        ┆ str        ┆   ┆ i64     ┆ f64      ┆ raw        ┆ i64   │
│             ┆            ┆            ┆            ┆   ┆         ┆          ┆ materia…   ┆       │
│             ┆            ┆            ┆            ┆   ┆         ┆          ┆ ---        ┆       │
│             ┆            ┆            ┆            ┆   ┆         ┆          ┆ f64        ┆       │
╞═════════════╪════════════╪════════════╪════════════╪═══╪═════════╪══════════╪════════════╪═══════╡
│ ADM         ┆ rotterdam_ ┆ food       ┆ Reference  ┆ … ┆ null    ┆ null     ┆ null       ┆ null  │
│ Europoort   ┆ moerdijk   ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ ADM         ┆ rotterdam_ ┆ food       ┆ Reference  ┆ … ┆ null    ┆ null     ┆ null       ┆ null  │
│ Europoort   ┆ moerdijk   ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ ADM         ┆ rotterdam_ ┆ food       ┆ Reference  ┆ … ┆ null    ┆ null     ┆ null       ┆ null  │
│ Europoort   ┆ moerdijk   ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ ADM         ┆ rotterdam_ ┆ food       ┆ Reference  ┆ … ┆ null    ┆ null     ┆ null       ┆ null  │
│ Europoort   ┆ moerdijk   ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ ADM         ┆ rotterdam_ ┆ food       ┆ Groen gas  ┆ … ┆ 0       ┆ 0.0      ┆ 0.0        ┆ 0     │
│ Europoort   ┆ moerdijk   ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ …           ┆ …          ┆ …          ┆ …          ┆ … ┆ …       ┆ …        ┆ …          ┆ …     │
│ Zeeland     ┆ zeeland_we ┆ refineries ┆ Midden     ┆ … ┆ 0       ┆ 0.0      ┆ 0.0        ┆ null  │
│ Refinery    ┆ st_brabant ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ Zeeland     ┆ zeeland_we ┆ refineries ┆ Groen gas  ┆ … ┆ 0       ┆ 0.0      ┆ 0.0        ┆ null  │
│ Refinery    ┆ st_brabant ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ Zeeland     ┆ zeeland_we ┆ refineries ┆ Waterstof  ┆ … ┆ 0       ┆ 0.0      ┆ 0.0        ┆ null  │
│ Refinery    ┆ st_brabant ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ Zeeland     ┆ zeeland_we ┆ refineries ┆ VT         ┆ … ┆ 0       ┆ 0.0      ┆ 0.0        ┆ null  │
│ Refinery    ┆ st_brabant ┆            ┆            ┆   ┆         ┆          ┆            ┆       │
│ Zeeland     ┆ zeeland_we ┆ refineries ┆ Elektrific ┆ … ┆ 0       ┆ 0.0      ┆ 0.0        ┆ null  │
│ Refinery    ┆ st_brabant ┆            ┆ atie       ┆   ┆         ┆          ┆            ┆       │
└─────────────┴────────────┴────────────┴────────────┴───┴─────────┴──────────┴────────────┴───────┘

In [56]:
df_enriched.write_excel('test_master.xlsx')

In [57]:

clusters = mapping.select(pl.col('Sector')).unique()
clusters.to_series().to_list()

['other_metals',
 'refineries',
 'inorganic_base_chemicals',
 'central_ict',
 'other',
 'textile_and_leather',
 'mining_and_quarrying',
 'Construction',
 'machinery',
 'organic_base_chemicals',
 'Wood and wood products',
 'aluminium',
 'paper',
 'food',
 'other_chemicals',
 'transport_equipment',
 'non_metallic_minerals',
 'gebruiker_stuurt_op_via_api',
 'steel']

In [58]:
cluster_map = {
    'nzkg': 'nzkg',
    'NZKG': 'nzkg',
    'rotterdam_moerdijk': 'rotterdam_moerdijk',
    'Rotterdam-Moerdijk': 'rotterdam_moerdijk',
    'rotterdam moerdijk': 'rotterdam_moerdijk',
    'cluster_6': 'cluster_6',
    'Cluster 6': 'cluster_6',
    'cluster 6': 'cluster_6',
    'noord_nederland': 'noord_nederland',
    'Noord-Nederland': 'noord_nederland',
    'noord nederland': 'noord_nederland',
    'zeeland_west_brabant': 'zeeland_west_brabant',
    'Zeeland-West-Brabant': 'zeeland_west_brabant',
    'zeeland west brabant': 'zeeland_west_brabant',
    'Gebruiker stuurt op via API': 'gebruiker_stuurt_op_via_api',
}

# Sector normalizations
sector_map = {
    'Organic base': 'organic_base_chemicals',
    'Organic base chemicals': 'organic_base_chemicals',
    'organic_base_chemicals': 'organic_base_chemicals',
    'Inorganic base chemicals': 'inorganic_base_chemicals',
    'inorganic_base_chemicals': 'inorganic_base_chemicals',
    'Other chemicals': 'other_chemicals',
    'other_chemicals': 'other_chemicals',
    'Other chemical': 'other_chemicals',
    'Food': 'food',
    'food': 'food',
    'Steel': 'steel',
    'steel': 'steel',
    'Refineries': 'refineries',
    'refineries': 'refineries',
    'Aluminium': 'aluminium',
    'aluminium': 'aluminium',
    'Paper': 'paper',
    'paper': 'paper',
    'Non-metallic minerals': 'non_metallic_minerals',
    'non_metallic_minerals': 'non_metallic_minerals',
    'non metallic minerals': 'non_metallic_minerals',
    'Other metals': 'other_metals',
    'other_metals': 'other_metals',
    'other metals': 'other_metals',
    'Machinery': 'machinery',
    'machinery': 'machinery',
    'Textiles and leather': 'textile_and_leather',
    'textile_and_leather': 'textile_and_leather',
    'Textile and leather': 'textile_and_leather',
    'Transport equipment': 'transport_equipment',
    'transport_equipment': 'transport_equipment',
    'Mining and quarrying': 'mining_and_quarrying',
    'mining_and_quarrying': 'mining_and_quarrying',
    'Central ICT': 'central_ict',
    'central_ict': 'central_ict',
    'Other': 'other',
    'other': 'other',
    'Gebruiker stuurt op via API': 'gebruiker_stuurt_op_via_api',
}

In [59]:
result = mapping.with_columns([
    pl.col("Cluster")
    .replace(cluster_map),

    pl.col('Sector').replace(sector_map)
])

In [60]:
result

shape: (531, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ Name      ┆ Name refo ┆ Sector    ┆ Cluster   ┆ … ┆ DSH plant ┆ category  ┆ New site ┆ Bottom-up │
│ ---       ┆ rmatted   ┆ ---       ┆ ---       ┆   ┆ id        ┆ ---       ┆ ---      ┆ ---       │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ bool     ┆ bool      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ A12 CPP   ┆ a12_cpp_p ┆ other     ┆ cluster_6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Petrogas  ┆ etrogas_e ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ EP Nether ┆ p_netherl ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│ land…     ┆ and…      ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Aardgasbu ┆ aardgasbu ┆ other     ┆ cluster_6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ ffer Zuid ┆ ffer_zuid ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ wending   ┆ wending   ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Abbott    ┆ abbott_he ┆ other_che ┆ cluster_6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Healthcar ┆ althcare_ ┆ micals    ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ e         ┆ products  ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│ Products  ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ Abbott    ┆ abbott_la ┆ food      ┆ cluster_6 ┆ … ┆ null      ┆ Bestaande ┆ false    ┆ false     │
│ Laborator ┆ boratorie ┆           ┆           ┆   ┆           ┆ niet-bott ┆          ┆           │
│ ies       ┆ s         ┆           ┆           ┆   ┆           ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆ sites     ┆          ┆           │
│ ADM       ┆ adm_europ ┆ food      ┆ rotterdam ┆ … ┆ 527be9a2- ┆ Bestaande ┆ false    ┆ false     │
│ Europoort ┆ oort      ┆           ┆ _moerdijk ┆   ┆ 5258-4cda ┆ niet-bott ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆ -89cb-b48 ┆ om-up     ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆ 520…      ┆ sites     ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ ##new_cc_ ┆ ##new_cc_ ┆ gebruiker ┆ gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site230## ┆ site230## ┆ _stuurt_o ┆ _stuurt_o ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ p_via_api ┆ p_via_api ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ gebruiker ┆ gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site231## ┆ site231## ┆ _stuurt_o ┆ _stuurt_o ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ p_via_api ┆ p_via_api ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ gebruiker ┆ gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site232## ┆ site232## ┆ _stuurt_o ┆ _stuurt_o ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ p_via_api ┆ p_via_api ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ gebruiker ┆ gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site233## ┆ site233## ┆ _stuurt_o ┆ _stuurt_o ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ p_via_api ┆ p_via_api ┆   ┆           ┆           ┆          ┆           │
│ ##new_cc_ ┆ ##new_cc_ ┆ gebruiker ┆ gebruiker ┆ … ┆ null      ┆ New sites ┆ true     ┆ false     │
│ site234## ┆ site234## ┆ _stuurt_o ┆ _stuurt_o ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆ p_via_api ┆ p_via_api ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘