In [1]:
import polars as pl
import pandas as pd
from utils import *

In [2]:
i = 'c00446f2-df0c-466d-a5c9-82f434123d17'


# test the project sheet
projects_df_init = pl.from_pandas(pd.read_csv(
    '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/dsh/20260508_new/datasafehouse-projectdata-export_emissions_df20260423.csv'))

project_vals_init = pl.from_pandas(pd.read_csv(
    '/home/307920@ontw.alfa.local/projects/epn-ma-master/data/dsh/20260508_new/datasafehouse-projectdata-export_utilities_df20260423.csv'
))


aux_details = get_project_details(projects_df_init, i)
print('x')

aux_values = get_project_values(project_vals_init, i)
print('xx')

No EAN code found.
No EAN code found.
No EAN code found.
No EAN code found.
No EAN code found.
No EAN code found.
No EAN code found.
No EAN code found.
No EAN code found.
x
xx

In [8]:
type(aux_details)

polars.dataframe.frame.DataFrame

In [4]:
aux_values.head(3)

shape: (3, 22)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ Project    ┆ Type       ┆ CO2        ┆ CO2 (bio) ┆ … ┆ Natural   ┆ Hydrogen  ┆ Hydrogen  ┆ Other │
│ name       ┆ ---        ┆ (fossil)   ┆ CCU/CCS   ┆   ┆ Gas       ┆ ( >98%    ┆ ( <98%    ┆ ---   │
│ ---        ┆ str        ┆ CCU/CCS    ┆ ---       ┆   ┆ ---       ┆ vol.%)    ┆ vol.%)    ┆ null  │
│ str        ┆            ┆ ---        ┆ null      ┆   ┆ f64       ┆ (LHV)     ┆ (LHV)     ┆       │
│            ┆            ┆ null       ┆           ┆   ┆           ┆ ---       ┆ ---       ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆ f64       ┆ null      ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 12. Mothba ┆ Delta      ┆ null       ┆ null      ┆ … ┆ -5.0      ┆ null      ┆ null      ┆ null  │
│ lling      ┆ demand     ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ Gasturbine ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ G30…       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 12. Mothba ┆ Delta      ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ lling      ┆ captive    ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ Gasturbine ┆ use        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ G30…       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 12. Mothba ┆ Delta      ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ lling      ┆ production ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ Gasturbine ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ G30…       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [9]:
joined = aux_values.join(aux_details,
                  on='Project name',
                  how='left')

joined = joined.select(list(dict.fromkeys(aux_details.columns + aux_values.columns))).sort('Project name')

shape: (36, 33)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ Project    ┆ Project    ┆ Descriptio ┆ Project   ┆ … ┆ Natural   ┆ Hydrogen  ┆ Hydrogen  ┆ Other │
│ name       ┆ Type       ┆ n          ┆ phase     ┆   ┆ Gas       ┆ ( >98%    ┆ ( <98%    ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ vol.%)    ┆ vol.%)    ┆ null  │
│ str        ┆ str        ┆ null       ┆ str       ┆   ┆ f64       ┆ (LHV)     ┆ (LHV)     ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆ ---       ┆ ---       ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆ f64       ┆ null      ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 01. BiBoBo ┆ Hydrogen   ┆ null       ┆ Define    ┆ … ┆ -13.0     ┆ null      ┆ null      ┆ null  │
│ adj        ┆ as fuel    ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 01. BiBoBo ┆ Hydrogen   ┆ null       ┆ Define    ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ adj        ┆ as fuel    ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 01. BiBoBo ┆ Hydrogen   ┆ null       ┆ Define    ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ adj        ┆ as fuel    ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 01. BiBoBo ┆ Hydrogen   ┆ null       ┆ Define    ┆ … ┆ null      ┆ -13.0     ┆ null      ┆ null  │
│ adj        ┆ as fuel    ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 02. Imoto  ┆ Change in  ┆ null       ┆ Operate   ┆ … ┆ -32.0     ┆ null      ┆ null      ┆ null  │
│ light      ┆ products   ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│            ┆ or         ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│            ┆ producti…  ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ 11. Denkai ┆ Hydrogen   ┆ null       ┆ Appraise  ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ (Mizu)     ┆ as fuel    ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 12. Mothba ┆ Electricit ┆ null       ┆ Appraise  ┆ … ┆ -5.0      ┆ null      ┆ null      ┆ null  │
│ lling      ┆ y          ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ Gasturbine ┆ production ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ G30…       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 12. Mothba ┆ Electricit ┆ null       ┆ Appraise  ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ lling      ┆ y          ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ Gasturbine ┆ production ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ G30…       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 12. Mothba ┆ Electricit ┆ null       ┆ Appraise  ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ lling      ┆ y          ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ Gasturbine ┆ production ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ G30…       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 12. Mothba ┆ Electricit ┆ null       ┆ Appraise  ┆ … ┆ null      ┆ null      ┆ null      ┆ null  │
│ lling      ┆ y          ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ Gasturbine ┆ production ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ G30…       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘